const assert=require('node:assert/strict');
const {Readable}=require('node:stream');
let route=null;try{route=require('../src/routes/bookings');}catch{}
assert.ok(route,'bookings route module is required');
const {handleBookingsRoute}=route;
function res(){return{status:null,headers:{},body:'',writeHead(s,h={}){this.status=s;this.headers={...this.headers,...h};},end(b=''){this.body+=b||'';}};}
function req(method,url,body=''){const r=Readable.from([Buffer.from(body)]);r.method=method;r.url=url;r.headers=method==='POST'?{'content-type':'application/x-www-form-urlencoded',origin:'https://preston.run'}:{};return r;}
function store(){const data={trips:[{id:'t1',user_id:'u1',title:'ANZ',status:'upcoming'}],trip_segments:[{id:'s1',user_id:'u1',trip_id:'t1',title:'Flight',position:1}],bookings:[{id:'b1',user_id:'u1',trip_id:null,segment_id:null,title:'Belle in Bowral',booking_type:'accommodation',status:'confirmed',position:1,time_zone:'Australia/Sydney',source_metadata:{source:'gmail',manual_fields:[]}}]};function builder(table){let mode='select',payload=null,filters=[],orders=[];const b={select(){return b;},eq(k,v){filters.push([k,v]);return b;},is(k,v){filters.push([k,v]);return b;},order(k,o){orders.push([k,o]);return b;},insert(v){mode='insert';payload=v;return b;},update(v){mode='update';payload=v;return b;},delete(){mode='delete';return b;},single(){if(mode==='insert'){const row={id:`new-${table}-${data[table].length+1}`,...payload};data[table].push(row);return Promise.resolve({data:row,error:null});}return Promise.resolve({data:null,error:null});},maybeSingle(){let row=data[table].find(x=>filters.every(([k,v])=>x[k]===v))||null;if(mode==='update'&&row)Object.assign(row,payload);if(mode==='delete'&&row)data[table].splice(data[table].indexOf(row),1);return Promise.resolve({data:row,error:null});},then(resolve,reject){let rows=data[table].filter(x=>filters.every(([k,v])=>x[k]===v));return Promise.resolve({data:rows,error:null}).then(resolve,reject);}};return b;}return{data,auth:{getUser:async()=>({data:{user:{id:'u1',email:'owner@example.com'}},error:null}),signOut:async()=>{}},from:t=>builder(t)};}
const config={siteUrl:'https://preston.run',ownerGoogleEmail:'owner@example.com'};
(async()=>{const s=store();let r=res();assert.equal(await handleBookingsRoute(req('GET','/bookings'),r,{supabase:s,config}),true);assert.equal(r.status,200);assert.match(r.body,/Belle in Bowral/);assert.match(r.body,/Unlinked/);
r=res();await handleBookingsRoute(req('GET','/trips/t1/bookings/new'),r,{supabase:s,config});assert.equal(r.status,200);assert.match(r.body,/value="t1" selected/);
r=res();await handleBookingsRoute(req('POST','/bookings','title=Train&booking_type=transport&status=confirmed&position=1&time_zone=Australia%2FSydney'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(r.headers.location,'/bookings?created=1');assert.equal(s.data.bookings.length,2);assert.equal(s.data.bookings[1].trip_id,null);
r=res();await handleBookingsRoute(req('POST','/trips/t1/bookings','title=Hotel&booking_type=accommodation&status=confirmed&position=1&time_zone=Australia%2FSydney'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(r.headers.location,'/trips/t1','nested booking create should return to the selected trip');assert.equal(s.data.bookings.at(-1).trip_id,'t1');
r=res();await handleBookingsRoute(req('POST','/bookings/b1','title=Belle&booking_type=accommodation&status=confirmed&position=1&trip_id=t1&segment_id=s1&time_zone=Australia%2FSydney'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(s.data.bookings[0].trip_id,'t1');assert.equal(s.data.bookings[0].segment_id,'s1');
r=res();await handleBookingsRoute(req('POST','/bookings/b1','title=Belle&booking_type=accommodation&status=confirmed&position=1&trip_id=t1&segment_id=missing&time_zone=Australia%2FSydney'),r,{supabase:s,config});assert.equal(r.status,400);assert.match(r.body,/selected segment/i);
r=res();const bad=req('POST','/bookings','title=X&booking_type=other&status=confirmed&time_zone=Australia%2FSydney');bad.headers.origin='https://evil.example';await handleBookingsRoute(bad,r,{supabase:s,config});assert.equal(r.status,403);
console.log('bookings route tests passed');})().catch(e=>{console.error(e);process.exit(1)});