const assert=require('node:assert/strict');
const {determineScanWindow,runGmailScan}=require('../src/services/gmail-scan-runner');

const initial=determineScanWindow({first_scan_completed_at:null},new Date('2026-09-13T12:00:00Z'),12);assert.equal(initial.scanType,'initial');assert.equal(initial.after,'2025/09/13');
const incremental=determineScanWindow({first_scan_completed_at:'2026-09-13T01:00:00Z',checkpoint_received_at:'2026-09-12T00:00:00Z'},new Date('2026-09-13T12:00:00Z'),12);assert.equal(incremental.scanType,'manual_incremental');assert.equal(incremental.after,'2026/09/12');
const enc=s=>Buffer.from(s).toString('base64url');
function provider({pdf=false}={}){return{listMessages:async()=>({messages:[{id:'m1'}]}),getMessage:async()=>({id:'m1',threadId:'t1',labelIds:['INBOX'],internalDate:String(Date.parse('2026-09-13T00:00:00Z')),snippet:'Short travel snippet',payload:{mimeType:'multipart/mixed',headers:[{name:'From',value:'Qantas <noreply@qantas.com>'},{name:'Subject',value:'Flight booking'}],parts:[{mimeType:'text/plain',body:{data:enc('Full body booking reference ECECAB Sydney to Brisbane on 18Dec26')}},...(pdf?[{filename:'ticket.pdf',mimeType:'application/pdf',body:{attachmentId:'att1'}}]:[])]}}),getAttachment:async()=>({data:enc('pdf bytes')})};}
function persistence(processed=[]){return{startScan:async()=>({id:'scan1'}),findExistingSource:async()=>null,upsertSource:async row=>{processed.push(row.gmail_message_id);return{id:'src1',...row};},updateSourceStatus:async()=>{},upsertAttachment:async()=>({id:'att-row'}),insertFacts:async facts=>facts,finishScan:async()=>{},failScan:async()=>{},updateScanProgress:async()=>{}};}

(async()=>{
  let extractedText='';const processed=[];const bookingCalls=[];
  const result=await runGmailScan({supabase:{},userId:'u1',connection:{id:'conn1',gmail_account_email:'me@example.com',first_scan_completed_at:null},provider:provider(),config:{scannerVersion:'s1',parserVersion:'p1',initialLookbackMonths:12},existingTrips:[{id:'trip1'}],persistence:persistence(processed),intentClassifier:()=>({intent:'trip',reason:'travel'}),bookingExtractor:(envelope,opts)=>{extractedText=envelope.text;assert.equal(opts.parserVersion,'p1');return{candidate:{provider:'Qantas',confirmation_reference:'ECECAB',booking_type:'flight',title:'Sydney → Brisbane flight'},facts:[{fact_type:'booking.identity',parser_version:'p1'}]};},bookingActions:{processBooking:async args=>{bookingCalls.push(args);return{booking:{id:'b1'},created:true,linkDecision:{kind:'review'}};}}});
  assert.equal(result.status,'succeeded');assert.deepEqual(processed,['m1']);assert.equal(result.tripCount,1);assert.equal(result.recordsCreatedCount,1);assert.match(extractedText,/Full body booking reference ECECAB/);assert.match(extractedText,/Short travel snippet/);assert.equal(bookingCalls.length,1);assert.equal(bookingCalls[0].source.id,'src1');assert.equal(bookingCalls[0].candidate.confirmation_reference,'ECECAB');assert.equal(bookingCalls[0].trips[0].id,'trip1');

  let pdfEvidence='';
  const pdf=await runGmailScan({supabase:{},userId:'u1',connection:{id:'conn1',gmail_account_email:'me@example.com',first_scan_completed_at:null},provider:provider({pdf:true}),config:{scannerVersion:'s1',parserVersion:'p1',initialLookbackMonths:12,extractNativePdfText:async()=>({status:'processed',text:'PDF itinerary confirmation PDF123',reason:null})},existingTrips:[],persistence:persistence([]),intentClassifier:()=>({intent:'trip',reason:'travel'}),bookingExtractor:envelope=>{pdfEvidence=envelope.text;return{candidate:{provider:'Qantas',booking_type:'flight',title:'Flight'},facts:[]};},bookingActions:{processBooking:async()=>({booking:{id:'b2'},created:true,linkDecision:{kind:'review'}})}});
  assert.equal(pdf.status,'succeeded');assert.match(pdfEvidence,/PDF itinerary confirmation PDF123/,'PDF text must be available before booking extraction');

  const ignored=await runGmailScan({supabase:{},userId:'u1',connection:{id:'conn1',gmail_account_email:'me@example.com',first_scan_completed_at:null},provider:provider(),config:{scannerVersion:'s1',parserVersion:'p1',initialLookbackMonths:12},persistence:persistence([]),intentClassifier:()=>({intent:'ignore',reason:'none'}),bookingActions:{processBooking:async()=>assert.fail('ignored mail must not create bookings')}});assert.equal(ignored.status,'succeeded');assert.equal(ignored.ignoredCount,1);

  const pages=[];const pageProcessed=[];
  const paged=await runGmailScan({supabase:{},userId:'u1',connection:{id:'conn1',gmail_account_email:'me@example.com',first_scan_completed_at:null},provider:{listMessages:async(_q,token)=>{pages.push(token||'first');return token==='p2'?{messages:[{id:'m2'}]}:{messages:[{id:'m1'}],nextPageToken:'p2'};},getMessage:async id=>({id,threadId:`t-${id}`,labelIds:['INBOX'],internalDate:String(Date.parse('2026-09-13T00:00:00Z')),snippet:'ordinary',payload:{headers:[{name:'Subject',value:'ordinary'}]}})},config:{scannerVersion:'s1',parserVersion:'p1',initialLookbackMonths:12},persistence:persistence(pageProcessed),intentClassifier:()=>({intent:'ignore',reason:'none'})});assert.equal(paged.status,'succeeded');assert.deepEqual(pages,['first','p2']);assert.deepEqual(pageProcessed,['m1','m2']);

  const duplicateProcessed=[];const dupPersistence=persistence(duplicateProcessed);dupPersistence.findExistingSource=async()=>({id:'src-existing',processing_status:'processed'});
  const duplicate=await runGmailScan({supabase:{},userId:'u1',connection:{id:'conn1',gmail_account_email:'me@example.com',first_scan_completed_at:null},provider:provider(),config:{scannerVersion:'s1',parserVersion:'p1',initialLookbackMonths:12},persistence:dupPersistence,bookingActions:{processBooking:async()=>assert.fail('processed duplicate must not replay')}});assert.equal(duplicate.status,'succeeded');assert.deepEqual(duplicateProcessed,[]);
  console.log('gmail scan runner tests passed');
})().catch(e=>{console.error(e);process.exit(1)});
