const assert=require('node:assert/strict');
const {Readable}=require('node:stream');
const {handleLifeAdminRoute}=require('../src/routes/life-admin');
function res(){return{status:null,headers:{},body:'',writeHead(s,h={}){this.status=s;this.headers={...this.headers,...h};},end(b=''){this.body+=b||'';}};}
function req(method,url,body=''){const r=Readable.from([Buffer.from(body)]);r.method=method;r.url=url;r.headers=method==='POST'?{'content-type':'application/x-www-form-urlencoded',origin:'https://preston.run'}:{};return r;}
function store(owner=true){const data={people:[{id:'p1',user_id:'u1',name:'Alice',active:true}],life_items:[{id:'l1',user_id:'u1',title:'Licence',category:'renewal',status:'upcoming',due_at:'2026-10-01T00:00:00Z',starts_at:null,recurrence_rule:null,priority:'normal',notes:null,linked_person_id:'p1',source_metadata:{source:'manual'}}],tasks:[{id:'t1',user_id:'u1',title:'Pay fee',status:'open',due_at:'2026-09-30T00:00:00Z',priority:'high',linked_life_item_id:'l1',linked_person_id:null,linked_trip_id:null,notes:null}],trips:[{id:'trip1',user_id:'u1',title:'Chicago',status:'upcoming',start_date:'2026-10-01',end_date:'2026-10-10'}]};function builder(table){let mode='select',payload=null,filters=[];const b={select(){return b;},order(){return b;},insert(v){mode='insert';payload=v;return b;},update(v){mode='update';payload=v;return b;},delete(){mode='delete';return b;},eq(k,v){filters.push([k,v]);return b;},single(){if(mode==='insert'){const row={id:`new-${table}-${data[table].length+1}`,...payload};data[table].push(row);return Promise.resolve({data:row,error:null});}return Promise.resolve({data:null,error:null});},maybeSingle(){let row=data[table].find(x=>filters.every(([k,v])=>x[k]===v))||null;if(mode==='update'&&row)Object.assign(row,payload);if(mode==='delete'&&row)data[table].splice(data[table].indexOf(row),1);return Promise.resolve({data:row,error:null});},then(resolve,reject){const rows=data[table].filter(x=>filters.every(([k,v])=>x[k]===v));return Promise.resolve({data:rows,error:null}).then(resolve,reject);}};return b;}return{data,auth:{getUser:async()=>owner?{data:{user:{id:'u1',email:'owner@example.com'}},error:null}:{data:{user:null},error:null},signOut:async()=>{}},from:t=>builder(t)};}
const config={siteUrl:'https://preston.run',ownerGoogleEmail:'owner@example.com'};
(async()=>{let s=store(false),r=res();await handleLifeAdminRoute(req('GET','/life-admin'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(r.headers.location,'/');s=store(true);r=res();await handleLifeAdminRoute(req('GET','/life-admin'),r,{supabase:s,config});assert.equal(r.status,200);assert.match(r.body,/Licence/);assert.equal(r.headers['cache-control'],'private, no-store');
r=res();const bad=req('POST','/life-admin','title=X&category=renewal&status=upcoming&priority=normal');bad.headers.origin='https://evil.example';await handleLifeAdminRoute(bad,r,{supabase:s,config});assert.equal(r.status,403);assert.equal(s.data.life_items.length,1);
r=res();await handleLifeAdminRoute(req('POST','/life-admin','title=Passport+renewal&category=government&status=needs_action&due_at=2026-10-15&priority=high&linked_person_id=p1'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(r.headers.location,'/life-admin?created=1');assert.equal(s.data.life_items.length,2);assert.equal(s.data.life_items[1].user_id,'u1');assert.equal(s.data.life_items[1].source_metadata.source,'manual');assert.ok(s.data.life_items[1].source_metadata.manual_fields.includes('title'));assert.ok(s.data.life_items[1].source_metadata.manual_fields.includes('due_at'));
r=res();await handleLifeAdminRoute(req('POST','/life-admin','title=Bad+link&category=other&status=upcoming&priority=normal&linked_person_id=missing'),r,{supabase:s,config});assert.equal(r.status,400);assert.equal(s.data.life_items.length,2);
r=res();await handleLifeAdminRoute(req('POST','/life-admin','title=Bad+trip&category=event&status=upcoming&priority=normal&linked_trip_id=missing'),r,{supabase:s,config});assert.equal(r.status,400);assert.equal(s.data.life_items.length,2);assert.match(r.body,/selected trip/i);
r=res();await handleLifeAdminRoute(req('POST','/life-admin','title=Dinner+at+Yonder&category=event&status=upcoming&priority=normal&starts_at=2026-10-02T19%3A00&ends_at=2026-10-02T21%3A00&time_zone=America%2FChicago&location=West+Loop&provider=Yonder&confirmation_reference=DIN123&booking_url=https%3A%2F%2Fexample.com%2Freservation&linked_trip_id=trip1'),r,{supabase:s,config});assert.equal(r.status,302);const event=s.data.life_items.at(-1);assert.equal(event.linked_trip_id,'trip1');assert.equal(event.time_zone,'America/Chicago');assert.equal(event.location,'West Loop');assert.equal(event.provider,'Yonder');assert.equal(event.confirmation_reference,'DIN123');assert.equal(event.booking_url,'https://example.com/reservation');assert.ok(event.starts_at&&event.ends_at);
r=res();await handleLifeAdminRoute(req('GET',`/life-admin/${event.id}/edit`),r,{supabase:s,config});assert.equal(r.status,200);assert.match(r.body,/value="trip1" selected/);assert.match(r.body,/America\/Chicago/);
r=res();await handleLifeAdminRoute(req('POST','/tasks','title=Submit+form&status=open&priority=urgent&linked_life_item_id=l1&linked_trip_id=trip1'),r,{supabase:s,config});assert.equal(r.status,302);assert.equal(s.data.tasks.length,2);assert.equal(s.data.tasks[1].linked_life_item_id,'l1');assert.equal(s.data.tasks[1].linked_trip_id,'trip1');
r=res();await handleLifeAdminRoute(req('POST','/tasks','title=Bad+trip&status=open&priority=normal&linked_trip_id=missing'),r,{supabase:s,config});assert.equal(r.status,400);assert.equal(s.data.tasks.length,2);assert.match(r.body,/selected trip/i);
r=res();await handleLifeAdminRoute(req('GET','/tasks/new?trip_id=trip1'),r,{supabase:s,config});assert.equal(r.status,200);assert.match(r.body,/Chicago/);assert.match(r.body,/value="trip1" selected/);
r=res();await handleLifeAdminRoute(req('GET','/life-admin/l1'),r,{supabase:s,config});assert.equal(r.status,200);assert.match(r.body,/Pay fee/);
r=res();await handleLifeAdminRoute(req('GET','/life-admin/missing'),r,{supabase:s,config});assert.equal(r.status,404);
console.log('Life Admin route tests passed');})().catch(e=>{console.error(e);process.exit(1)});
