const assert=require('node:assert/strict');
const {renderLifeAdminPage,renderLifeItemPage,renderLifeItemFormPage,renderTaskFormPage}=require('../src/pages/life-admin');
const people=[{id:'p1',name:'Alice <Friend>'}];
const items=[{id:'l1',title:'Licence <renewal>',category:'renewal',status:'needs_action',due_at:'2026-09-12T00:00:00Z',starts_at:null,priority:'urgent',notes:'Pay & submit',linked_person_id:'p1'}];
const noDateItem={id:'l2',title:'No date item',category:'other',status:'upcoming',due_at:null,starts_at:null,priority:'normal',notes:null,linked_person_id:null};
const trips=[{id:'trip1',title:'Chicago & Milwaukee'}];
const tasks=[{id:'t1',title:'Upload form',status:'open',due_at:'2026-09-11T00:00:00Z',priority:'high',linked_life_item_id:'l1',linked_trip_id:'trip1'}];
const attention=[{type:'life_item',record:items[0],overdue:true},{type:'task',record:tasks[0],overdue:true}];
const coming=[{item:{...items[0],due_at:'2026-09-20T00:00:00Z',status:'upcoming'},date:new Date('2026-09-20T00:00:00Z'),daysAway:7}];
const html=renderLifeAdminPage({lifeItems:[...items,noDateItem],tasks,people,filter:'active',category:'renewal',needsAttention:attention,comingUp:coming,flash:'Saved'});
for(const text of ['Life Admin','Needs Attention','Coming Up','Add item','Add task','Licence &lt;renewal&gt;','Pay &amp; submit','Alice &lt;Friend&gt;','Overdue','Urgent'])assert.ok(html.includes(text),`missing ${text}`);
assert.match(html,/href="\/preston\.css"/);
assert.match(html,/class="site-header"/);
assert.match(html,/href="\/life-admin\?filter=renewal"[^>]*>Active<\/a>/);
assert.match(html,/filter=needs_action[^>]*>Needs attention<\/a>/);
assert.match(html,/filter=upcoming[^>]*>Upcoming<\/a>/);
assert.match(html,/filter=completed[^>]*>Completed<\/a>/);
assert.doesNotMatch(html,/>Renewals<\/a>/);
assert.doesNotMatch(html,/>Bills<\/a>/);
assert.match(html,/<select[^>]*name="category"[^>]*>/);
assert.match(html,/<option value="renewal" selected>Renewals<\/option>/);
assert.match(html,/class="row attention-row"[^>]*href="\/life-admin\/l1"/);
assert.match(html,/class="row attention-row task-row"[^>]*href="\/tasks\/t1\/edit"/);
assert.match(html,/class="card task-card"/);
assert.doesNotMatch(html,/No date item[\s\S]{0,160}No date/);
assert.ok(!html.includes('ppodolske@gmail.com'));
const detail=renderLifeItemPage({item:items[0],linkedTasks:tasks,person:people[0]});assert.match(detail,/Upload form/);assert.match(detail,/Add task/);assert.match(detail,/Edit item/);assert.doesNotMatch(detail,/Starts<\/span><strong>No date<\/strong>/);
const event={id:'e1',title:'Dinner at Yonder',category:'event',status:'upcoming',priority:'normal',starts_at:'2026-10-02T08:00:00.000Z',ends_at:'2026-10-02T10:00:00.000Z',time_zone:'America/Chicago',location:'West Loop',provider:'Yonder',confirmation_reference:'DIN123',booking_url:'https://example.com/reservation',linked_trip_id:'trip1',source_metadata:{source:'gmail',source_link:'https://mail.google.com/mail/u/me%40example.com/#all/msg1'}};
const eventDetail=renderLifeItemPage({item:event,linkedTasks:[],trip:trips[0]});
for(const x of ['Dinner at Yonder','West Loop','Yonder','DIN123','Chicago &amp; Milwaukee','/trips/trip1','Open booking','Open source email'])assert.ok(eventDetail.includes(x),`event detail missing ${x}`);
const gmailDetail=renderLifeItemPage({item:{...items[0],id:'g1',title:'Review Gmail: Reservation confirmed',source_metadata:{source:'gmail',source_link:'https://mail.google.com/mail/u/me%40example.com/#all/msg1'}},linkedTasks:[]});assert.match(gmailDetail,/Open source email/);assert.match(gmailDetail,/href="https:\/\/mail\.google\.com\/mail\/u\/me%40example\.com\/#all\/msg1"/);
const form=renderLifeItemFormPage({item:items[0],people,trips,mode:'edit',error:'Bad date',reminderSettings:{renewal_offsets:[60,30,14,7,1]},reminderOverride:null});assert.match(form,/action="\/life-admin\/l1"/);assert.match(form,/value="2026-09-12"/);assert.match(form,/Bad date/);assert.match(form,/Use global defaults/);assert.match(form,/Custom reminders/);assert.match(form,/60, 30, 14, 7, 1/);assert.match(form,/<label for="title">Title<\/label>/);
const eventForm=renderLifeItemFormPage({item:event,people,trips,mode:'edit'});
for(const x of ['name="linked_trip_id"','value="trip1" selected','Chicago &amp; Milwaukee','name="starts_at"','type="datetime-local"','name="ends_at"','name="time_zone"','America/Chicago','name="location"','West Loop','name="provider"','Yonder','name="confirmation_reference"','DIN123','name="booking_url"','https://example.com/reservation'])assert.ok(eventForm.includes(x),`event form missing ${x}`);
const custom=renderLifeItemFormPage({item:items[0],people,trips,mode:'edit',reminderSettings:{renewal_offsets:[60,30,14,7,1]},reminderOverride:{enabled:true,offsets:[21,5]}});assert.match(custom,/21, 5/);assert.match(custom,/Restore defaults/);
const taskForm=renderTaskFormPage({task:tasks[0],lifeItems:items,people,trips,mode:'edit'});assert.match(taskForm,/action="\/tasks\/t1"/);assert.match(taskForm,/value="l1" selected/);assert.match(taskForm,/name="linked_trip_id"/);assert.match(taskForm,/value="trip1" selected/);assert.match(taskForm,/Chicago &amp; Milwaukee/);assert.match(taskForm,/<label for="title">Title<\/label>/);
console.log('Life Admin page tests passed');