const assert = require('node:assert/strict');
const { renderLoginPage } = require('../src/pages/login');
const { renderHomePage } = require('../src/pages/home');
const login = renderLoginPage();
for (const expected of ['preston.ai','/assets/preston-ai-logo.png','/auth/google','/manifest.webmanifest','/icons/favicon-32.png']) assert.ok(login.includes(expected),`login missing ${expected}`);
for (const forbidden of ['Dose & Scale','State Parks','Archive','Website admin','Railway','id="condition"','birthday','Life Admin','Coming Up','Manage people']) assert.ok(!login.includes(forbidden), `login leaked ${forbidden}`);
const home = renderHomePage({user:{email:'owner@example.com',user_metadata:{full_name:'Preston Example'}},upcomingBirthdays:[{person:{name:'Alex',birth_year:null},daysAway:4,ageTurning:null},{person:{name:'Jordan',birth_year:1990},daysAway:10,ageTurning:37}]});
for (const expected of ['preston.ai','/assets/preston-ai-logo.png','Good morning','Dose & Scale','State Parks','Archive','Website admin','id="condition"','/auth/logout','v0.6.0','/manifest.webmanifest','Coming Up','Birthdays','Manage people','Alex','4 days','Turning 37']) assert.ok(home.includes(expected),`home missing ${expected}`);
assert.ok(!home.includes('owner@example.com'),'home should not expose owner email');
const unavailable=renderHomePage({user:{},birthdayDataUnavailable:true});assert.ok(unavailable.includes('Birthday data is temporarily unavailable.'));
console.log('page tests passed');
