const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {ALLOWED}=require('../src/http/static');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname,'../public/manifest.webmanifest'),'utf8'));
assert.equal(manifest.name,'preston.ai'); assert.equal(manifest.short_name,'preston.ai'); assert.equal(manifest.start_url,'/'); assert.equal(manifest.display,'standalone');
assert.ok(manifest.icons.some(i=>i.sizes==='192x192'));
assert.ok(manifest.icons.some(i=>i.sizes==='512x512' && !i.purpose));
assert.ok(manifest.icons.some(i=>i.sizes==='512x512' && i.purpose==='maskable'));
for (const icon of manifest.icons) assert.ok(fs.existsSync(path.join(__dirname,'../public',icon.src)),`missing ${icon.src}`);
for (const file of ['assets/preston-ai-logo.png','icons/favicon-32.png','icons/apple-touch-icon.png']) assert.ok(fs.existsSync(path.join(__dirname,'../public',file)),`missing ${file}`);
assert.equal(ALLOWED.get('/sw.js'),'sw.js');
assert.equal(ALLOWED.get('/notifications.js'),'notifications.js');
const sw=fs.readFileSync(path.join(__dirname,'../public/sw.js'),'utf8');
assert.match(sw,/addEventListener\(['"]push['"]/);
assert.match(sw,/showNotification/);
assert.match(sw,/addEventListener\(['"]notificationclick['"]/);
assert.match(sw,/openWindow|focus\(/);
console.log('pwa tests passed');
