const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const pkg=require('../package.json');
const {PRODUCT_NAME,VERSION,APPS}=require('../src/branding');
const {renderLoginPage}=require('../src/pages/login');
const {renderHomePage}=require('../src/pages/home');
assert.equal(pkg.version,'0.8.0');assert.equal(VERSION,'0.8.0');assert.equal(PRODUCT_NAME,'preston.ai');
for(const name of ['Dose & Scale','State Parks','Archive']) assert.ok(APPS.some(a=>a.name===name));
assert.equal(APPS.find(a=>a.name==='State Parks').url,'https://parks.preston.run');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../public/manifest.webmanifest'),'utf8'));assert.equal(manifest.name,'preston.ai');
const login=renderLoginPage();for(const forbidden of ['railway.com','Coming Up','Needs Attention','Life Admin','Manage people','Trips','/trips'])assert.ok(!login.includes(forbidden),`login leaked ${forbidden}`);
const home=renderHomePage({user:{},upcomingBirthdays:[],upcomingLifeItems:[],needsAttention:[],upcomingTrips:[]});for(const expected of ['id="condition"','Coming Up','Needs Attention','/people','/life-admin','Trips','/trips','Log out'])assert.ok(home.includes(expected),`home missing ${expected}`);
for(const file of ['src/routes/people.js','src/routes/life-admin.js','src/routes/trips.js','src/data/life-admin.js','src/data/tasks.js','src/data/trips.js','src/data/bookings.js','src/domain/trips.js','src/pages/trips.js'])assert.ok(fs.existsSync(path.join(__dirname,'..',file)),`missing ${file}`);
console.log('smoke tests passed');
