const {getAuthorizedOwner}=require('../auth/guard');
const {listBookings,getBooking,createBooking,updateBooking,deleteBooking}=require('../data/bookings');
const {listBookingLegs,getBookingLeg,createBookingLeg,updateBookingLeg,deleteBookingLeg}=require('../data/booking-legs');
const {listTrips,getTrip,listSegments,getSegment}=require('../data/trips');
const {validateBookingInput,validateBookingLegInput}=require('../domain/trips');
const {readForm,isSameOriginRequest}=require('../http/forms');
const {html,redirect,text}=require('../http/respond');
const {renderBookingsPage,renderBookingFormPage}=require('../pages/bookings');

async function owner(supabase,config,res){const auth=await getAuthorizedOwner(supabase,config);if(auth.user)return auth.user;if(auth.reason==='not_owner')await supabase.auth.signOut();redirect(res,'/');return null;}
function privateHtml(res,status,body){html(res,status,body,{'cache-control':'private, no-store'});}
function flash(url){if(url.searchParams.get('created'))return'Booking created.';if(url.searchParams.get('saved'))return'Booking saved.';if(url.searchParams.get('deleted'))return'Booking deleted.';return null;}
function bookingRaw(form,id,forcedTripId=null){return{id,trip_id:forcedTripId!==null?forcedTripId:(form.get('trip_id')||''),title:form.get('title')||'',booking_type:form.get('booking_type')||'',status:form.get('status')||'',position:form.get('position')||'1',segment_id:form.get('segment_id')||'',provider:form.get('provider')||'',confirmation_reference:form.get('confirmation_reference')||'',starts_at:form.get('starts_at')||'',ends_at:form.get('ends_at')||'',time_zone:form.get('time_zone')||'Australia/Sydney',location:form.get('location')||'',origin:form.get('origin')||'',destination:form.get('destination')||'',booking_url:form.get('booking_url')||'',notes:form.get('notes')||''};}
function legRaw(form){return{position:form.get('position')||'1',service_number:form.get('service_number')||'',origin:form.get('origin')||'',destination:form.get('destination')||'',departs_at:form.get('departs_at')||'',arrives_at:form.get('arrives_at')||'',departure_time_zone:form.get('departure_time_zone')||'Australia/Sydney',arrival_time_zone:form.get('arrival_time_zone')||form.get('departure_time_zone')||'Australia/Sydney'};}
async function validTrip(supabase,user,id){if(!id)return null;const row=await getTrip(supabase,user,id);if(!row)throw new Error('The selected trip is not available');return row;}
async function validSegment(supabase,user,id,tripId){if(!id)return null;if(!tripId)throw new Error('Select a trip before selecting a stage');const row=await getSegment(supabase,user,id);if(!row||row.trip_id!==tripId)throw new Error('The selected stage is not available for this trip');return row;}
async function formResources(supabase,user,tripId){const trips=await listTrips(supabase,user);const segments=tripId?await listSegments(supabase,user,tripId):[];return{trips,segments};}
function isBookingPath(path){return path==='/bookings'||path==='/bookings/new'||/^\/bookings\/[^/]+(?:\/edit|\/delete)?$/.test(path)||/^\/bookings\/[^/]+\/legs(?:\/[^/]+(?:\/delete)?)?$/.test(path)||/^\/trips\/[^/]+\/bookings(?:\/new)?$/.test(path);}

async function handleBookingsRoute(req,res,context){const{supabase,config}=context;let url;try{url=new URL(req.url,config.siteUrl);}catch{return false;}if(!isBookingPath(url.pathname))return false;const user=await owner(supabase,config,res);if(!user)return true;
  if(req.method==='GET'&&url.pathname==='/bookings'){try{const[bookings,trips]=await Promise.all([listBookings(supabase,user),listTrips(supabase,user)]);privateHtml(res,200,renderBookingsPage({bookings,trips,flash:flash(url)}));}catch{privateHtml(res,500,renderBookingsPage({flash:'Bookings are temporarily unavailable.'}));}return true;}
  if(req.method==='GET'&&url.pathname==='/bookings/new'){try{const tripId=url.searchParams.get('trip_id')||'';await validTrip(supabase,user,tripId);const{trips,segments}=await formResources(supabase,user,tripId);privateHtml(res,200,renderBookingFormPage({booking:{trip_id:tripId,position:1,booking_type:'other',status:'confirmed',time_zone:'Australia/Sydney'},trips,segments,legs:[],mode:'create'}));}catch(e){text(res,400,e.message||'The selected trip is not available',{'cache-control':'no-store'});}return true;}
  const nestedNew=url.pathname.match(/^\/trips\/([^/]+)\/bookings\/new$/);if(req.method==='GET'&&nestedNew){const tripId=decodeURIComponent(nestedNew[1]);redirect(res,`/bookings/new?trip_id=${encodeURIComponent(tripId)}`);return true;}
  const edit=url.pathname.match(/^\/bookings\/([^/]+)\/edit$/);if(req.method==='GET'&&edit){try{const booking=await getBooking(supabase,user,decodeURIComponent(edit[1]));if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const[{trips,segments},legs]=await Promise.all([formResources(supabase,user,booking.trip_id),listBookingLegs(supabase,user,booking.id)]);privateHtml(res,200,renderBookingFormPage({booking,trips,segments,legs,mode:'edit'}));}catch{text(res,500,'Bookings are temporarily unavailable',{'cache-control':'no-store'});}return true;}
  if(req.method!=='POST'){text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;}
  if(!isSameOriginRequest(req,config)){text(res,403,'Forbidden',{'cache-control':'no-store'});return true;}
  let data;try{data=await readForm(req);}catch(e){text(res,e.statusCode||400,'Invalid form request',{'cache-control':'no-store'});return true;}

  const legCreate=url.pathname.match(/^\/bookings\/([^/]+)\/legs$/);if(legCreate){const bookingId=decodeURIComponent(legCreate[1]);try{const booking=await getBooking(supabase,user,bookingId);if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const input=validateBookingLegInput(legRaw(data));await createBookingLeg(supabase,user,bookingId,input);redirect(res,`/bookings/${encodeURIComponent(bookingId)}/edit`);}catch(e){text(res,400,e.message||'Unable to save booking leg',{'cache-control':'no-store'});}return true;}
  const legDelete=url.pathname.match(/^\/bookings\/([^/]+)\/legs\/([^/]+)\/delete$/);if(legDelete){const bookingId=decodeURIComponent(legDelete[1]),legId=decodeURIComponent(legDelete[2]);try{const[booking,leg]=await Promise.all([getBooking(supabase,user,bookingId),getBookingLeg(supabase,user,legId)]);if(!booking||!leg||leg.booking_id!==bookingId){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await deleteBookingLeg(supabase,user,legId);redirect(res,`/bookings/${encodeURIComponent(bookingId)}/edit`);}catch{text(res,500,'Unable to delete booking leg',{'cache-control':'no-store'});}return true;}
  const legUpdate=url.pathname.match(/^\/bookings\/([^/]+)\/legs\/([^/]+)$/);if(legUpdate){const bookingId=decodeURIComponent(legUpdate[1]),legId=decodeURIComponent(legUpdate[2]);try{const[booking,leg]=await Promise.all([getBooking(supabase,user,bookingId),getBookingLeg(supabase,user,legId)]);if(!booking||!leg||leg.booking_id!==bookingId){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const input=validateBookingLegInput(legRaw(data));await updateBookingLeg(supabase,user,legId,input);redirect(res,`/bookings/${encodeURIComponent(bookingId)}/edit`);}catch(e){text(res,400,e.message||'Unable to save booking leg',{'cache-control':'no-store'});}return true;}

  const nestedCreate=url.pathname.match(/^\/trips\/([^/]+)\/bookings$/);
  if(url.pathname==='/bookings'||nestedCreate){const forcedTripId=nestedCreate?decodeURIComponent(nestedCreate[1]):null;let raw=bookingRaw(data,null,forcedTripId),input,trips=[],segments=[];try{input=validateBookingInput(raw);await validTrip(supabase,user,input.trip_id);await validSegment(supabase,user,input.segment_id,input.trip_id);({trips,segments}=await formResources(supabase,user,input.trip_id));}catch(e){try{({trips,segments}=await formResources(supabase,user,raw.trip_id));}catch{}privateHtml(res,400,renderBookingFormPage({booking:raw,trips,segments,legs:[],mode:'create',error:e.message}));return true;}try{await createBooking(supabase,user,input);redirect(res,nestedCreate?`/trips/${encodeURIComponent(input.trip_id)}`:'/bookings?created=1');}catch{privateHtml(res,500,renderBookingFormPage({booking:raw,trips,segments,legs:[],mode:'create',error:'Unable to save booking.'}));}return true;}
  const del=url.pathname.match(/^\/bookings\/([^/]+)\/delete$/);if(del){const id=decodeURIComponent(del[1]);try{const booking=await getBooking(supabase,user,id);if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await deleteBooking(supabase,user,id);redirect(res,'/bookings?deleted=1');}catch{text(res,500,'Unable to delete booking',{'cache-control':'no-store'});}return true;}
  const update=url.pathname.match(/^\/bookings\/([^/]+)$/);if(update){const id=decodeURIComponent(update[1]);let existing,raw=bookingRaw(data,id),input,trips=[],segments=[],legs=[];try{existing=await getBooking(supabase,user,id);if(!existing){text(res,404,'Not found',{'cache-control':'no-store'});return true;}input=validateBookingInput(raw);await validTrip(supabase,user,input.trip_id);await validSegment(supabase,user,input.segment_id,input.trip_id);({trips,segments}=await formResources(supabase,user,input.trip_id));legs=await listBookingLegs(supabase,user,id);}catch(e){try{({trips,segments}=await formResources(supabase,user,raw.trip_id));legs=existing?await listBookingLegs(supabase,user,id):[];}catch{}privateHtml(res,400,renderBookingFormPage({booking:{...(existing||{}),...raw},trips,segments,legs,mode:'edit',error:e.message}));return true;}try{await updateBooking(supabase,user,id,input);redirect(res,'/bookings?saved=1');}catch{privateHtml(res,500,renderBookingFormPage({booking:{...existing,...raw},trips,segments,legs,mode:'edit',error:'Unable to save booking.'}));}return true;}
  text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;
}

module.exports={handleBookingsRoute,bookingRaw,legRaw,isBookingPath};