const {getAuthorizedOwner}=require('../auth/guard');
const {listPeople,getPerson}=require('../data/people');
const {listLifeItems,getLifeItem,createLifeItem,updateLifeItem,deleteLifeItem}=require('../data/life-admin');
const {listTasks,getTask,createTask,updateTask,deleteTask}=require('../data/tasks');
const {listTrips,getTrip}=require('../data/trips');
const {getReminderSettings,getReminderOverride}=require('../data/reminders');
const {applyReminderOverrideForm}=require('./reminder-overrides');
const {validateLifeItemInput,validateTaskInput,getNeedsAttention,getComingUpLifeItems}=require('../domain/life-admin');
const {readForm,isSameOriginRequest}=require('../http/forms');
const {html,redirect,text}=require('../http/respond');
const {renderLifeAdminPage,renderLifeItemPage,renderLifeItemFormPage,renderTaskFormPage}=require('../pages/life-admin');

async function owner(supabase,config,res){const auth=await getAuthorizedOwner(supabase,config);if(auth.user)return auth.user;if(auth.reason==='not_owner')await supabase.auth.signOut();redirect(res,'/');return null;}
function flash(url){if(url.searchParams.get('created'))return'Created.';if(url.searchParams.get('saved'))return'Changes saved.';if(url.searchParams.get('deleted'))return'Deleted.';return null;}
function raw(form,id){return {id,title:form.get('title')||'',category:form.get('category')||'',status:form.get('status')||'',due_at:form.get('due_at')||'',starts_at:form.get('starts_at')||'',ends_at:form.get('ends_at')||'',time_zone:form.get('time_zone')||'',recurrence_rule:form.get('recurrence_rule')||'',priority:form.get('priority')||'',notes:form.get('notes')||'',linked_person_id:form.get('linked_person_id')||'',linked_life_item_id:form.get('linked_life_item_id')||'',linked_trip_id:form.get('linked_trip_id')||'',location:form.get('location')||'',provider:form.get('provider')||'',confirmation_reference:form.get('confirmation_reference')||'',booking_url:form.get('booking_url')||''};}
function filterItems(items,filter){switch(filter){case'needs_action':return items.filter(x=>x.status==='needs_action');case'upcoming':return items.filter(x=>x.status==='upcoming');case'renewal':case'bill':case'government':case'property':case'appointment':case'subscription':return items.filter(x=>x.category===filter);case'completed':return items.filter(x=>x.status==='completed');default:return items;}}
async function validPerson(supabase,id){if(!id)return null;const row=await getPerson(supabase,id);if(!row)throw new Error('Selected person is not available');return row;}
async function validLifeItem(supabase,id){if(!id)return null;const row=await getLifeItem(supabase,id);if(!row)throw new Error('Selected Life Admin item is not available');return row;}
async function validTrip(supabase,user,id){if(!id)return null;const row=await getTrip(supabase,user,id);if(!row)throw new Error('Selected trip is not available');return row;}
async function resources(supabase){const [lifeItems,tasks,people]=await Promise.all([listLifeItems(supabase),listTasks(supabase),listPeople(supabase)]);return{lifeItems,tasks,people};}
async function lifeFormResources(supabase,user){const[people,trips]=await Promise.all([listPeople(supabase),listTrips(supabase,user)]);return{people,trips};}
async function taskResources(supabase,user){const [lifeItems,people,trips]=await Promise.all([listLifeItems(supabase),listPeople(supabase),listTrips(supabase,user)]);return{lifeItems,people,trips};}
async function reminderState(supabase,userId,id){const[settings,override]=await Promise.all([getReminderSettings(supabase,userId),getReminderOverride(supabase,userId,'life_item',id)]);return{reminderSettings:settings||{},reminderOverride:override};}
async function form(req){return readForm(req);}
function privateHtml(res,status,body){html(res,status,body,{'cache-control':'private, no-store'});}

async function handleLifeAdminRoute(req,res,context){const{supabase,config}=context;let url;try{url=new URL(req.url,config.siteUrl);}catch{return false;}const lifePath=url.pathname==='/life-admin'||url.pathname==='/life-admin/new'||/^\/life-admin\/[^/]+(?:\/edit|\/delete)?$/.test(url.pathname);const taskPath=url.pathname==='/tasks'||url.pathname==='/tasks/new'||/^\/tasks\/[^/]+(?:\/edit|\/delete)?$/.test(url.pathname);if(!lifePath&&!taskPath)return false;const user=await owner(supabase,config,res);if(!user)return true;
if(req.method==='GET'&&url.pathname==='/life-admin'){try{const{lifeItems,tasks,people}=await resources(supabase);const filter=url.searchParams.get('filter')||'all';privateHtml(res,200,renderLifeAdminPage({lifeItems:filterItems(lifeItems,filter),tasks,people,filter,needsAttention:getNeedsAttention({lifeItems,tasks}),comingUp:getComingUpLifeItems(lifeItems,new Date(),90),flash:flash(url)}));}catch{privateHtml(res,500,renderLifeAdminPage({flash:'Life Admin is temporarily unavailable.'}));}return true;}
if(req.method==='GET'&&url.pathname==='/life-admin/new'){try{const r=await lifeFormResources(supabase,user);privateHtml(res,200,renderLifeItemFormPage({item:{category:'other',status:'upcoming',priority:'normal'},people:r.people,trips:r.trips,mode:'create'}));}catch{privateHtml(res,500,renderLifeItemFormPage({error:'Life Admin is temporarily unavailable.'}));}return true;}
const detail=url.pathname.match(/^\/life-admin\/([^/]+)$/);if(req.method==='GET'&&detail){try{const id=decodeURIComponent(detail[1]),item=await getLifeItem(supabase,id);if(!item){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const [tasks,person,trip]=await Promise.all([listTasks(supabase),item.linked_person_id?getPerson(supabase,item.linked_person_id):Promise.resolve(null),item.linked_trip_id?getTrip(supabase,user,item.linked_trip_id):Promise.resolve(null)]);privateHtml(res,200,renderLifeItemPage({item,linkedTasks:tasks.filter(t=>t.linked_life_item_id===id),person,trip}));}catch{text(res,500,'Life Admin is temporarily unavailable',{'cache-control':'no-store'});}return true;}
const edit=url.pathname.match(/^\/life-admin\/([^/]+)\/edit$/);if(req.method==='GET'&&edit){try{const id=decodeURIComponent(edit[1]),item=await getLifeItem(supabase,id);if(!item){text(res,404,'Not found',{'cache-control':'no-store'});return true;}let state={};try{state=await reminderState(supabase,user.id,id);}catch{}const r=await lifeFormResources(supabase,user);privateHtml(res,200,renderLifeItemFormPage({item,people:r.people,trips:r.trips,mode:'edit',...state}));}catch{text(res,500,'Life Admin is temporarily unavailable',{'cache-control':'no-store'});}return true;}
if(req.method==='GET'&&url.pathname==='/tasks/new'){try{const r=await taskResources(supabase,user);const preset=url.searchParams.get('life_item_id')||'',tripPreset=url.searchParams.get('trip_id')||'';if(preset)await validLifeItem(supabase,preset);if(tripPreset)await validTrip(supabase,user,tripPreset);privateHtml(res,200,renderTaskFormPage({task:{status:'open',priority:'normal',linked_life_item_id:preset,linked_trip_id:tripPreset},lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'create'}));}catch{privateHtml(res,400,renderTaskFormPage({error:'The selected link is not available.'}));}return true;}
const taskEdit=url.pathname.match(/^\/tasks\/([^/]+)\/edit$/);if(req.method==='GET'&&taskEdit){try{const task=await getTask(supabase,decodeURIComponent(taskEdit[1]));if(!task){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const r=await taskResources(supabase,user);privateHtml(res,200,renderTaskFormPage({task,lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'edit'}));}catch{text(res,500,'Tasks are temporarily unavailable',{'cache-control':'no-store'});}return true;}
if(req.method==='POST'){if(!isSameOriginRequest(req,config)){text(res,403,'Forbidden',{'cache-control':'no-store'});return true;}let data;try{data=await form(req);}catch(e){text(res,e.statusCode||400,'Invalid form request',{'cache-control':'no-store'});return true;}
if(url.pathname==='/life-admin'){let input;try{input=validateLifeItemInput(raw(data));await Promise.all([validPerson(supabase,input.linked_person_id),validTrip(supabase,user,input.linked_trip_id)]);}catch(e){const r=await lifeFormResources(supabase,user).catch(()=>({people:[],trips:[]}));privateHtml(res,400,renderLifeItemFormPage({item:raw(data),people:r.people,trips:r.trips,mode:'create',error:e.message}));return true;}try{await createLifeItem(supabase,user,input);redirect(res,'/life-admin?created=1');}catch{const r=await lifeFormResources(supabase,user).catch(()=>({people:[],trips:[]}));privateHtml(res,500,renderLifeItemFormPage({item:raw(data),people:r.people,trips:r.trips,mode:'create',error:'Unable to save item.'}));}return true;}
const del=url.pathname.match(/^\/life-admin\/([^/]+)\/delete$/);if(del){try{const ok=await deleteLifeItem(supabase,user,decodeURIComponent(del[1]));if(!ok){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,'/life-admin?deleted=1');}catch{text(res,409,'Unable to delete item while linked records exist',{'cache-control':'no-store'});}return true;}
const upd=url.pathname.match(/^\/life-admin\/([^/]+)$/);if(upd){const id=decodeURIComponent(upd[1]);let input;try{const existing=await getLifeItem(supabase,id);if(!existing){text(res,404,'Not found',{'cache-control':'no-store'});return true;}input=validateLifeItemInput(raw(data,id));await Promise.all([validPerson(supabase,input.linked_person_id),validTrip(supabase,user,input.linked_trip_id)]);}catch(e){const r=await lifeFormResources(supabase,user).catch(()=>({people:[],trips:[]}));privateHtml(res,400,renderLifeItemFormPage({item:raw(data,id),people:r.people,trips:r.trips,mode:'edit',error:e.message}));return true;}try{const row=await updateLifeItem(supabase,user,id,input);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await applyReminderOverrideForm(supabase,user.id,'life_item',id,data);redirect(res,'/life-admin?saved=1');}catch(e){let state={};try{state=await reminderState(supabase,user.id,id);}catch{}const r=await lifeFormResources(supabase,user).catch(()=>({people:[],trips:[]}));privateHtml(res,400,renderLifeItemFormPage({item:raw(data,id),people:r.people,trips:r.trips,mode:'edit',error:e&&e.message?e.message:'Unable to save changes.',...state}));}return true;}
if(url.pathname==='/tasks'){let input;try{input=validateTaskInput(raw(data));await Promise.all([validPerson(supabase,input.linked_person_id),validLifeItem(supabase,input.linked_life_item_id),validTrip(supabase,user,input.linked_trip_id)]);}catch(e){const r=await taskResources(supabase,user).catch(()=>({lifeItems:[],people:[],trips:[]}));privateHtml(res,400,renderTaskFormPage({task:raw(data),lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'create',error:e.message}));return true;}try{await createTask(supabase,user,input);redirect(res,'/life-admin?created=1');}catch{const r=await taskResources(supabase,user).catch(()=>({lifeItems:[],people:[],trips:[]}));privateHtml(res,500,renderTaskFormPage({task:raw(data),lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'create',error:'Unable to save task.'}));}return true;}
const taskDel=url.pathname.match(/^\/tasks\/([^/]+)\/delete$/);if(taskDel){try{const ok=await deleteTask(supabase,user,decodeURIComponent(taskDel[1]));if(!ok){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,'/life-admin?deleted=1');}catch{text(res,500,'Unable to delete task',{'cache-control':'no-store'});}return true;}
const taskUpd=url.pathname.match(/^\/tasks\/([^/]+)$/);if(taskUpd){const id=decodeURIComponent(taskUpd[1]);let input;try{input=validateTaskInput(raw(data,id));await Promise.all([validPerson(supabase,input.linked_person_id),validLifeItem(supabase,input.linked_life_item_id),validTrip(supabase,user,input.linked_trip_id)]);}catch(e){const r=await taskResources(supabase,user).catch(()=>({lifeItems:[],people:[],trips:[]}));privateHtml(res,400,renderTaskFormPage({task:raw(data,id),lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'edit',error:e.message}));return true;}try{const row=await updateTask(supabase,user,id,input);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,'/life-admin?saved=1');}catch{const r=await taskResources(supabase,user).catch(()=>({lifeItems:[],people:[],trips:[]}));privateHtml(res,500,renderTaskFormPage({task:raw(data,id),lifeItems:r.lifeItems,people:r.people,trips:r.trips,mode:'edit',error:'Unable to save task.'}));}return true;}}
text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;}

module.exports={handleLifeAdminRoute,filterItems,raw};