const {getAuthorizedOwner}=require('../auth/guard');
const {listTrips,getTrip,createTrip,updateTrip,archiveTrip,unarchiveTrip,deleteTrip,listSegments,getSegment,createSegment,updateSegment,deleteSegment}=require('../data/trips');
const {listBookings}=require('../data/bookings');
const {listBookingLegsByBookingIds}=require('../data/booking-legs');
const {listLifeItemsByTrip}=require('../data/life-admin');
const {listTasks}=require('../data/tasks');
const {getReminderSettings,getReminderOverride}=require('../data/reminders');
const {applyReminderOverrideForm}=require('./reminder-overrides');
const {validateTripInput,validateSegmentInput,buildItinerary,getUpcomingTrips}=require('../domain/trips');
const {travelTypeInventory,selectNextItineraryEntry}=require('../domain/travel-presenter');
const {readForm,isSameOriginRequest}=require('../http/forms');
const {html,redirect,text}=require('../http/respond');
const {renderTripsPage,renderTripDetailPage,renderTripFormPage,renderSegmentFormPage}=require('../pages/trips');

async function owner(supabase,config,res){const auth=await getAuthorizedOwner(supabase,config);if(auth.user)return auth.user;if(auth.reason==='not_owner')await supabase.auth.signOut();redirect(res,'/');return null;}
function privateHtml(res,status,body){html(res,status,body,{'cache-control':'private, no-store'});}
function flash(url){if(url.searchParams.get('created'))return'Created.';if(url.searchParams.get('saved'))return'Changes saved.';if(url.searchParams.get('deleted'))return'Deleted.';if(url.searchParams.get('archived'))return'Trip archived.';if(url.searchParams.get('unarchived'))return'Trip unarchived.';return null;}
function tripRaw(form,id){return{id,title:form.get('title')||'',status:form.get('status')||'',start_date:form.get('start_date')||'',end_date:form.get('end_date')||'',destination_label:form.get('destination_label')||'',destination_city:form.get('destination_city')||'',destination_region:form.get('destination_region')||'',destination_country:form.get('destination_country')||'',notes:form.get('notes')||''};}
function segmentRaw(form,id,tripId){return{id,trip_id:tripId,title:form.get('title')||'',segment_type:form.get('segment_type')||'',position:form.get('position')||'1',origin:form.get('origin')||'',destination:form.get('destination')||'',starts_at:form.get('starts_at')||'',ends_at:form.get('ends_at')||'',time_zone:form.get('time_zone')||'Australia/Sydney',notes:form.get('notes')||''};}
async function validTrip(supabase,user,id){const row=await getTrip(supabase,user,id);if(!row)throw Object.assign(new Error('Trip not found'),{statusCode:404});return row;}
async function reminderState(supabase,userId,id){const[settings,override]=await Promise.all([getReminderSettings(supabase,userId),getReminderOverride(supabase,userId,'trip',id)]);return{reminderSettings:settings||{},reminderOverride:override};}
function isTripPath(path){return path==='/trips'||path==='/trips/new'||path==='/trips/archived'||/^\/trips\/[^/]+(?:\/edit|\/delete|\/archive|\/unarchive|\/segments\/new|\/segments|\/bookings\/new)?$/.test(path)||/^\/segments\/[^/]+(?:\/edit|\/delete)?$/.test(path);}
function todayKey(now=new Date()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const m=Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return`${m.year}-${m.month}-${m.day}`;}
function splitActiveTrips(trips,now=new Date()){const upcoming=getUpcomingTrips(trips,now,3650),ids=new Set(upcoming.map(x=>x.id)),today=todayKey(now);for(const trip of trips){if(ids.has(trip.id))continue;if(!trip.start_date&&!['completed','cancelled'].includes(trip.status)){upcoming.push(trip);ids.add(trip.id);}}const past=trips.filter(t=>!ids.has(t.id)&&((t.end_date&&t.end_date<today)||['completed','cancelled'].includes(t.status)));return{upcoming,past};}
function sortArchived(rows){return rows.slice().sort((a,b)=>String(b.end_date||'').localeCompare(String(a.end_date||''))||String(b.start_date||'').localeCompare(String(a.start_date||''))||String(b.archived_at||'').localeCompare(String(a.archived_at||''))||String(a.title||'').localeCompare(String(b.title||'')));}

async function handleTripsRoute(req,res,context){const{supabase,config}=context;let url;try{url=new URL(req.url,config.siteUrl);}catch{return false;}if(!isTripPath(url.pathname))return false;const user=await owner(supabase,config,res);if(!user)return true;
  if(req.method==='GET'&&url.pathname==='/trips'){try{const trips=await listTrips(supabase,user,{archiveState:'active'}),split=splitActiveTrips(trips,new Date());privateHtml(res,200,renderTripsPage({trips,upcoming:split.upcoming,past:split.past,flash:flash(url)}));}catch{privateHtml(res,500,renderTripsPage({flash:'Trips are temporarily unavailable.'}));}return true;}
  if(req.method==='GET'&&url.pathname==='/trips/archived'){try{const trips=sortArchived(await listTrips(supabase,user,{archiveState:'archived'}));privateHtml(res,200,renderTripsPage({trips,archived:true,flash:flash(url)}));}catch{privateHtml(res,500,renderTripsPage({archived:true,flash:'Archived trips are temporarily unavailable.'}));}return true;}
  if(req.method==='GET'&&url.pathname==='/trips/new'){privateHtml(res,200,renderTripFormPage({trip:{status:'planning'},mode:'create'}));return true;}
  const nestedNew=url.pathname.match(/^\/trips\/([^/]+)\/bookings\/new$/);if(req.method==='GET'&&nestedNew){const tripId=decodeURIComponent(nestedNew[1]);redirect(res,`/bookings/new?trip_id=${encodeURIComponent(tripId)}`);return true;}
  const detail=url.pathname.match(/^\/trips\/([^/]+)$/);if(req.method==='GET'&&detail){try{const id=decodeURIComponent(detail[1]),trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const[segments,bookings,events,tasks]=await Promise.all([listSegments(supabase,user,id),listBookings(supabase,user,{tripId:id}),listLifeItemsByTrip(supabase,user,id),listTasks(supabase)]);const bookingLegs=await listBookingLegsByBookingIds(supabase,user,bookings.map(b=>b.id)),itinerary=buildItinerary({segments,bookings,events}),nextEntry=selectNextItineraryEntry(itinerary,new Date()),inventory=travelTypeInventory({bookings,events});privateHtml(res,200,renderTripDetailPage({trip,segments,bookings,events,itinerary,bookingLegs,inventory,nextEntry,tasks:tasks.filter(t=>t.linked_trip_id===id)}));}catch{text(res,500,'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
  const tripEdit=url.pathname.match(/^\/trips\/([^/]+)\/edit$/);if(req.method==='GET'&&tripEdit){try{const id=decodeURIComponent(tripEdit[1]),trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}let state={};try{state=await reminderState(supabase,user.id,id);}catch{}privateHtml(res,200,renderTripFormPage({trip,mode:'edit',...state}));}catch{text(res,500,'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
  const newStage=url.pathname.match(/^\/trips\/([^/]+)\/segments\/new$/);if(req.method==='GET'&&newStage){try{const trip=await validTrip(supabase,user,decodeURIComponent(newStage[1]));privateHtml(res,200,renderSegmentFormPage({trip,segment:{position:1,segment_type:'travel',time_zone:'Australia/Sydney'},mode:'create'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
  const stageEdit=url.pathname.match(/^\/segments\/([^/]+)\/edit$/);if(req.method==='GET'&&stageEdit){try{const segment=await getSegment(supabase,user,decodeURIComponent(stageEdit[1]));if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const trip=await validTrip(supabase,user,segment.trip_id);privateHtml(res,200,renderSegmentFormPage({segment,trip,mode:'edit'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
  if(req.method!=='POST'){text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;}
  if(!isSameOriginRequest(req,config)){text(res,403,'Forbidden',{'cache-control':'no-store'});return true;}
  let data;try{data=await readForm(req);}catch(e){text(res,e.statusCode||400,'Invalid form request',{'cache-control':'no-store'});return true;}

  const archive=url.pathname.match(/^\/trips\/([^/]+)\/archive$/);if(archive){const id=decodeURIComponent(archive[1]);try{const row=await archiveTrip(supabase,user,id);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,`/trips/${encodeURIComponent(id)}`);}catch{text(res,500,'Unable to archive trip',{'cache-control':'no-store'});}return true;}
  const unarchive=url.pathname.match(/^\/trips\/([^/]+)\/unarchive$/);if(unarchive){const id=decodeURIComponent(unarchive[1]);try{const row=await unarchiveTrip(supabase,user,id);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,`/trips/${encodeURIComponent(id)}`);}catch{text(res,500,'Unable to unarchive trip',{'cache-control':'no-store'});}return true;}
  if(url.pathname==='/trips'){let input;try{input=validateTripInput(tripRaw(data));}catch(e){privateHtml(res,400,renderTripFormPage({trip:tripRaw(data),mode:'create',error:e.message}));return true;}try{const row=await createTrip(supabase,user,input);redirect(res,`/trips/${encodeURIComponent(row.id)}?created=1`);}catch{privateHtml(res,500,renderTripFormPage({trip:tripRaw(data),mode:'create',error:'Unable to save trip.'}));}return true;}
  const tripDelete=url.pathname.match(/^\/trips\/([^/]+)\/delete$/);if(tripDelete){const id=decodeURIComponent(tripDelete[1]);try{const trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const[tasks,bookings,segments,events]=await Promise.all([listTasks(supabase),listBookings(supabase,user,{tripId:id}),listSegments(supabase,user,id),listLifeItemsByTrip(supabase,user,id)]);if(tasks.some(t=>t.linked_trip_id===id)){text(res,409,'Unlink linked tasks before deleting this trip',{'cache-control':'no-store'});return true;}if(events.length){text(res,409,'Unlink linked Life Admin events before deleting this trip',{'cache-control':'no-store'});return true;}if(bookings.length){text(res,409,'Unlink linked bookings before deleting this trip',{'cache-control':'no-store'});return true;}if(segments.length){text(res,409,'Delete trip stages before deleting this trip',{'cache-control':'no-store'});return true;}const ok=await deleteTrip(supabase,user,id);if(!ok){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,'/trips?deleted=1');}catch{text(res,409,'Unable to delete trip while linked records exist',{'cache-control':'no-store'});}return true;}
  const tripUpdate=url.pathname.match(/^\/trips\/([^/]+)$/);if(tripUpdate){const id=decodeURIComponent(tripUpdate[1]);let input;try{const existing=await getTrip(supabase,user,id);if(!existing){text(res,404,'Not found',{'cache-control':'no-store'});return true;}input=validateTripInput(tripRaw(data,id));}catch(e){privateHtml(res,e.statusCode||400,renderTripFormPage({trip:tripRaw(data,id),mode:'edit',error:e.message}));return true;}try{const row=await updateTrip(supabase,user,id,input);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await applyReminderOverrideForm(supabase,user.id,'trip',id,data);redirect(res,`/trips/${encodeURIComponent(id)}?saved=1`);}catch(e){let state={};try{state=await reminderState(supabase,user.id,id);}catch{}privateHtml(res,400,renderTripFormPage({trip:tripRaw(data,id),mode:'edit',error:e&&e.message?e.message:'Unable to save changes.',...state}));}return true;}
  const stageCreate=url.pathname.match(/^\/trips\/([^/]+)\/segments$/);if(stageCreate){const tripId=decodeURIComponent(stageCreate[1]);let trip,input;try{trip=await validTrip(supabase,user,tripId);input=validateSegmentInput(segmentRaw(data,null,tripId));}catch(e){if(e.statusCode===404){text(res,404,'Not found',{'cache-control':'no-store'});return true;}privateHtml(res,400,renderSegmentFormPage({trip:trip||{id:tripId,title:'Trip'},segment:segmentRaw(data,null,tripId),mode:'create',error:e.message}));return true;}try{await createSegment(supabase,user,tripId,input);redirect(res,`/trips/${encodeURIComponent(tripId)}`);}catch{privateHtml(res,500,renderSegmentFormPage({trip,segment:segmentRaw(data,null,tripId),mode:'create',error:'Unable to save stage.'}));}return true;}
  const stageDelete=url.pathname.match(/^\/segments\/([^/]+)\/delete$/);if(stageDelete){const id=decodeURIComponent(stageDelete[1]);try{const segment=await getSegment(supabase,user,id);if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const bookings=await listBookings(supabase,user,{tripId:segment.trip_id});if(bookings.some(b=>b.segment_id===id)){text(res,409,'Reassign or unlink linked bookings before deleting this stage',{'cache-control':'no-store'});return true;}await deleteSegment(supabase,user,id);redirect(res,`/trips/${encodeURIComponent(segment.trip_id)}`);}catch{text(res,409,'Unable to delete stage while linked bookings exist',{'cache-control':'no-store'});}return true;}
  const stageUpdate=url.pathname.match(/^\/segments\/([^/]+)$/);if(stageUpdate){const id=decodeURIComponent(stageUpdate[1]);let segment,trip,input;try{segment=await getSegment(supabase,user,id);if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}trip=await validTrip(supabase,user,segment.trip_id);input=validateSegmentInput(segmentRaw(data,id,segment.trip_id));}catch(e){if(!segment&&e.statusCode===404){text(res,404,'Not found',{'cache-control':'no-store'});return true;}privateHtml(res,400,renderSegmentFormPage({trip:trip||{id:segment&&segment.trip_id,title:'Trip'},segment:segmentRaw(data,id,segment&&segment.trip_id),mode:'edit',error:e.message}));return true;}try{await updateSegment(supabase,user,id,input);redirect(res,`/trips/${encodeURIComponent(segment.trip_id)}`);}catch{privateHtml(res,500,renderSegmentFormPage({trip,segment:segmentRaw(data,id,segment.trip_id),mode:'edit',error:'Unable to save stage.'}));}return true;}
  text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;
}

module.exports={handleTripsRoute,tripRaw,segmentRaw,isTripPath,splitActiveTrips,sortArchived};
