const {getAuthorizedOwner}=require('../auth/guard');
const {listTrips,getTrip,createTrip,updateTrip,deleteTrip,listSegments,getSegment,createSegment,updateSegment,deleteSegment}=require('../data/trips');
const {listBookings,getBooking,createBooking,updateBooking,deleteBooking}=require('../data/bookings');
const {listTasks}=require('../data/tasks');
const {getReminderSettings,getReminderOverride}=require('../data/reminders');
const {applyReminderOverrideForm}=require('./reminder-overrides');
const {validateTripInput,validateSegmentInput,validateBookingInput,buildItinerary,getUpcomingTrips}=require('../domain/trips');
const {readForm,isSameOriginRequest}=require('../http/forms');
const {html,redirect,text}=require('../http/respond');
const {renderTripsPage,renderTripDetailPage,renderTripFormPage,renderSegmentFormPage,renderBookingFormPage}=require('../pages/trips');

async function owner(supabase,config,res){const auth=await getAuthorizedOwner(supabase,config);if(auth.user)return auth.user;if(auth.reason==='not_owner')await supabase.auth.signOut();redirect(res,'/');return null;}
function privateHtml(res,status,body){html(res,status,body,{'cache-control':'private, no-store'});}
function flash(url){if(url.searchParams.get('created'))return'Created.';if(url.searchParams.get('saved'))return'Changes saved.';if(url.searchParams.get('deleted'))return'Deleted.';return null;}
function tripRaw(form,id){return{id,title:form.get('title')||'',status:form.get('status')||'',start_date:form.get('start_date')||'',end_date:form.get('end_date')||'',notes:form.get('notes')||''};}
function segmentRaw(form,id,tripId){return{id,trip_id:tripId,title:form.get('title')||'',segment_type:form.get('segment_type')||'',position:form.get('position')||'1',origin:form.get('origin')||'',destination:form.get('destination')||'',starts_at:form.get('starts_at')||'',ends_at:form.get('ends_at')||'',time_zone:form.get('time_zone')||'Australia/Sydney',notes:form.get('notes')||''};}
function bookingRaw(form,id,tripId){return{id,trip_id:tripId,title:form.get('title')||'',booking_type:form.get('booking_type')||'',status:form.get('status')||'',position:form.get('position')||'1',segment_id:form.get('segment_id')||'',provider:form.get('provider')||'',confirmation_reference:form.get('confirmation_reference')||'',starts_at:form.get('starts_at')||'',ends_at:form.get('ends_at')||'',time_zone:form.get('time_zone')||'Australia/Sydney',location:form.get('location')||'',booking_url:form.get('booking_url')||'',notes:form.get('notes')||''};}
async function validTrip(supabase,user,id){const row=await getTrip(supabase,user,id);if(!row)throw Object.assign(new Error('Trip not found'),{statusCode:404});return row;}
async function validSegment(supabase,user,id,tripId){if(!id)return null;const row=await getSegment(supabase,user,id);if(!row||row.trip_id!==tripId)throw new Error('The selected segment is not available for this trip');return row;}
async function reminderState(supabase,userId,id){const[settings,override]=await Promise.all([getReminderSettings(supabase,userId),getReminderOverride(supabase,userId,'trip',id)]);return{reminderSettings:settings||{},reminderOverride:override};}
function isTripPath(path){return path==='/trips'||path==='/trips/new'||/^\/trips\/[^/]+(?:\/edit|\/delete|\/segments\/new|\/segments|\/bookings\/new|\/bookings)?$/.test(path)||/^\/segments\/[^/]+(?:\/edit|\/delete)?$/.test(path)||/^\/bookings\/[^/]+(?:\/edit|\/delete)?$/.test(path);}

async function handleTripsRoute(req,res,context){const{supabase,config}=context;let url;try{url=new URL(req.url,config.siteUrl);}catch{return false;}if(!isTripPath(url.pathname))return false;const user=await owner(supabase,config,res);if(!user)return true;
if(req.method==='GET'&&url.pathname==='/trips'){try{const trips=await listTrips(supabase,user);privateHtml(res,200,renderTripsPage({trips,upcoming:getUpcomingTrips(trips,new Date(),180),flash:flash(url)}));}catch{privateHtml(res,500,renderTripsPage({flash:'Trips are temporarily unavailable.'}));}return true;}
if(req.method==='GET'&&url.pathname==='/trips/new'){privateHtml(res,200,renderTripFormPage({trip:{status:'planning'},mode:'create'}));return true;}
const detail=url.pathname.match(/^\/trips\/([^/]+)$/);if(req.method==='GET'&&detail){try{const id=decodeURIComponent(detail[1]),trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const[segments,bookings,tasks]=await Promise.all([listSegments(supabase,user,id),listBookings(supabase,user,id),listTasks(supabase)]);privateHtml(res,200,renderTripDetailPage({trip,segments,bookings,itinerary:buildItinerary({segments,bookings}),tasks:tasks.filter(t=>t.linked_trip_id===id)}));}catch{text(res,500,'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
const tripEdit=url.pathname.match(/^\/trips\/([^/]+)\/edit$/);if(req.method==='GET'&&tripEdit){try{const id=decodeURIComponent(tripEdit[1]),trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}let state={};try{state=await reminderState(supabase,user.id,id);}catch{}privateHtml(res,200,renderTripFormPage({trip,mode:'edit',...state}));}catch{text(res,500,'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
const newSegment=url.pathname.match(/^\/trips\/([^/]+)\/segments\/new$/);if(req.method==='GET'&&newSegment){try{const trip=await validTrip(supabase,user,decodeURIComponent(newSegment[1]));privateHtml(res,200,renderSegmentFormPage({trip,segment:{position:1,segment_type:'travel',time_zone:'Australia/Sydney'},mode:'create'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
const segmentEdit=url.pathname.match(/^\/segments\/([^/]+)\/edit$/);if(req.method==='GET'&&segmentEdit){try{const segment=await getSegment(supabase,user,decodeURIComponent(segmentEdit[1]));if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const trip=await validTrip(supabase,user,segment.trip_id);privateHtml(res,200,renderSegmentFormPage({segment,trip,mode:'edit'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
const newBooking=url.pathname.match(/^\/trips\/([^/]+)\/bookings\/new$/);if(req.method==='GET'&&newBooking){try{const tripId=decodeURIComponent(newBooking[1]),trip=await validTrip(supabase,user,tripId),segments=await listSegments(supabase,user,tripId);privateHtml(res,200,renderBookingFormPage({trip,segments,booking:{position:1,booking_type:'other',status:'confirmed',time_zone:'Australia/Sydney'},mode:'create'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
const bookingEdit=url.pathname.match(/^\/bookings\/([^/]+)\/edit$/);if(req.method==='GET'&&bookingEdit){try{const booking=await getBooking(supabase,user,decodeURIComponent(bookingEdit[1]));if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const trip=await validTrip(supabase,user,booking.trip_id),segments=await listSegments(supabase,user,booking.trip_id);privateHtml(res,200,renderBookingFormPage({booking,trip,segments,mode:'edit'}));}catch(e){text(res,e.statusCode||500,e.statusCode===404?'Not found':'Trips are temporarily unavailable',{'cache-control':'no-store'});}return true;}
if(req.method==='POST'){
if(!isSameOriginRequest(req,config)){text(res,403,'Forbidden',{'cache-control':'no-store'});return true;}let data;try{data=await readForm(req);}catch(e){text(res,e.statusCode||400,'Invalid form request',{'cache-control':'no-store'});return true;}
if(url.pathname==='/trips'){let input;try{input=validateTripInput(tripRaw(data));}catch(e){privateHtml(res,400,renderTripFormPage({trip:tripRaw(data),mode:'create',error:e.message}));return true;}try{const row=await createTrip(supabase,user,input);redirect(res,`/trips/${encodeURIComponent(row.id)}?created=1`);}catch{privateHtml(res,500,renderTripFormPage({trip:tripRaw(data),mode:'create',error:'Unable to save trip.'}));}return true;}
const tripDelete=url.pathname.match(/^\/trips\/([^/]+)\/delete$/);if(tripDelete){const id=decodeURIComponent(tripDelete[1]);try{const trip=await getTrip(supabase,user,id);if(!trip){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const tasks=await listTasks(supabase);if(tasks.some(t=>t.linked_trip_id===id)){text(res,409,'Unlink linked tasks before deleting this trip',{'cache-control':'no-store'});return true;}const ok=await deleteTrip(supabase,user,id);if(!ok){text(res,404,'Not found',{'cache-control':'no-store'});return true;}redirect(res,'/trips?deleted=1');}catch{text(res,409,'Unable to delete trip while linked records exist',{'cache-control':'no-store'});}return true;}
const tripUpdate=url.pathname.match(/^\/trips\/([^/]+)$/);if(tripUpdate){const id=decodeURIComponent(tripUpdate[1]);let input;try{const existing=await getTrip(supabase,user,id);if(!existing){text(res,404,'Not found',{'cache-control':'no-store'});return true;}input=validateTripInput(tripRaw(data,id));}catch(e){privateHtml(res,e.statusCode||400,renderTripFormPage({trip:tripRaw(data,id),mode:'edit',error:e.message}));return true;}try{const row=await updateTrip(supabase,user,id,input);if(!row){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await applyReminderOverrideForm(supabase,user.id,'trip',id,data);redirect(res,`/trips/${encodeURIComponent(id)}?saved=1`);}catch(e){let state={};try{state=await reminderState(supabase,user.id,id);}catch{}privateHtml(res,400,renderTripFormPage({trip:tripRaw(data,id),mode:'edit',error:e&&e.message?e.message:'Unable to save changes.',...state}));}return true;}
const segmentCreate=url.pathname.match(/^\/trips\/([^/]+)\/segments$/);if(segmentCreate){const tripId=decodeURIComponent(segmentCreate[1]);let trip,input;try{trip=await validTrip(supabase,user,tripId);input=validateSegmentInput(segmentRaw(data,null,tripId));}catch(e){if(e.statusCode===404){text(res,404,'Not found',{'cache-control':'no-store'});return true;}privateHtml(res,400,renderSegmentFormPage({trip:trip||{id:tripId,title:'Trip'},segment:segmentRaw(data,null,tripId),mode:'create',error:e.message}));return true;}try{await createSegment(supabase,user,tripId,input);redirect(res,`/trips/${encodeURIComponent(tripId)}`);}catch{privateHtml(res,500,renderSegmentFormPage({trip,segment:segmentRaw(data,null,tripId),mode:'create',error:'Unable to save segment.'}));}return true;}
const segmentDelete=url.pathname.match(/^\/segments\/([^/]+)\/delete$/);if(segmentDelete){const id=decodeURIComponent(segmentDelete[1]);try{const segment=await getSegment(supabase,user,id);if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}const bookings=await listBookings(supabase,user,segment.trip_id);if(bookings.some(b=>b.segment_id===id)){text(res,409,'Reassign or unlink linked bookings before deleting this segment',{'cache-control':'no-store'});return true;}await deleteSegment(supabase,user,id);redirect(res,`/trips/${encodeURIComponent(segment.trip_id)}`);}catch{text(res,409,'Unable to delete segment while linked bookings exist',{'cache-control':'no-store'});}return true;}
const segmentUpdate=url.pathname.match(/^\/segments\/([^/]+)$/);if(segmentUpdate){const id=decodeURIComponent(segmentUpdate[1]);let segment,trip,input;try{segment=await getSegment(supabase,user,id);if(!segment){text(res,404,'Not found',{'cache-control':'no-store'});return true;}trip=await validTrip(supabase,user,segment.trip_id);input=validateSegmentInput(segmentRaw(data,id,segment.trip_id));}catch(e){if(!segment&&e.statusCode===404){text(res,404,'Not found',{'cache-control':'no-store'});return true;}privateHtml(res,400,renderSegmentFormPage({trip:trip||{id:segment&&segment.trip_id,title:'Trip'},segment:segmentRaw(data,id,segment&&segment.trip_id),mode:'edit',error:e.message}));return true;}try{await updateSegment(supabase,user,id,input);redirect(res,`/trips/${encodeURIComponent(segment.trip_id)}`);}catch{privateHtml(res,500,renderSegmentFormPage({trip,segment:segmentRaw(data,id,segment.trip_id),mode:'edit',error:'Unable to save segment.'}));}return true;}
const bookingCreate=url.pathname.match(/^\/trips\/([^/]+)\/bookings$/);if(bookingCreate){const tripId=decodeURIComponent(bookingCreate[1]);let trip,segments=[],input;try{trip=await validTrip(supabase,user,tripId);segments=await listSegments(supabase,user,tripId);input=validateBookingInput(bookingRaw(data,null,tripId));await validSegment(supabase,user,input.segment_id,tripId);}catch(e){if(e.statusCode===404){text(res,404,'Not found',{'cache-control':'no-store'});return true;}privateHtml(res,400,renderBookingFormPage({trip:trip||{id:tripId,title:'Trip'},segments,booking:bookingRaw(data,null,tripId),mode:'create',error:e.message}));return true;}try{await createBooking(supabase,user,tripId,input);redirect(res,`/trips/${encodeURIComponent(tripId)}`);}catch{privateHtml(res,500,renderBookingFormPage({trip,segments,booking:bookingRaw(data,null,tripId),mode:'create',error:'Unable to save booking.'}));}return true;}
const bookingDelete=url.pathname.match(/^\/bookings\/([^/]+)\/delete$/);if(bookingDelete){const id=decodeURIComponent(bookingDelete[1]);try{const booking=await getBooking(supabase,user,id);if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}await deleteBooking(supabase,user,id);redirect(res,`/trips/${encodeURIComponent(booking.trip_id)}`);}catch{text(res,500,'Unable to delete booking',{'cache-control':'no-store'});}return true;}
const bookingUpdate=url.pathname.match(/^\/bookings\/([^/]+)$/);if(bookingUpdate){const id=decodeURIComponent(bookingUpdate[1]);let booking,trip,segments=[],input;try{booking=await getBooking(supabase,user,id);if(!booking){text(res,404,'Not found',{'cache-control':'no-store'});return true;}trip=await validTrip(supabase,user,booking.trip_id);segments=await listSegments(supabase,user,booking.trip_id);input=validateBookingInput(bookingRaw(data,id,booking.trip_id));await validSegment(supabase,user,input.segment_id,booking.trip_id);}catch(e){privateHtml(res,400,renderBookingFormPage({trip:trip||{id:booking&&booking.trip_id,title:'Trip'},segments,booking:bookingRaw(data,id,booking&&booking.trip_id),mode:'edit',error:e.message}));return true;}try{await updateBooking(supabase,user,id,input);redirect(res,`/trips/${encodeURIComponent(booking.trip_id)}`);}catch{privateHtml(res,500,renderBookingFormPage({trip,segments,booking:bookingRaw(data,id,booking.trip_id),mode:'edit',error:'Unable to save booking.'}));}return true;}}
text(res,405,'Method not allowed',{'cache-control':'no-store'});return true;}

module.exports={handleTripsRoute,tripRaw,segmentRaw,bookingRaw};