'use strict';
const {utcToLocalDateTime}=require('../domain/date-time');
const {renderShell,escapeHtml:esc}=require('../ui/shell');
const {buttonLink,emptyState,flashMessage,card,statusChip,label}=require('../ui/components');
const {textField,selectField,textareaField}=require('../ui/forms');
const TIME_ZONES=['Australia/Sydney','Australia/Adelaide','Australia/Darwin','Australia/Perth','Pacific/Auckland','America/Chicago','America/New_York','America/Los_Angeles','UTC'];
function pairs(values){return values.map(v=>[v,label(v)]);}
function tripOptions(trips){return [['','No trip'],...trips.map(t=>[t.id,t.title])];}
function segmentOptions(segments){return [['','None'],...segments.map(s=>[s.id,s.title])];}
function inputLocal(v,z){try{return v?utcToLocalDateTime(v,z||'Australia/Sydney'):'';}catch{return'';}}
function fieldInput({name,label:text,value='',type='text',required=false,min,list=''}){return `<div class="field"><label for="${esc(name)}">${esc(text)}</label><input id="${esc(name)}" name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"${required?' required':''}${min!==undefined?` min="${esc(min)}"`:''}${list?` list="${esc(list)}"`:''}></div>`;}
function timeZoneList(){return `<datalist id="booking-time-zones">${TIME_ZONES.map(z=>`<option value="${esc(z)}"></option>`).join('')}</datalist>`;}
function bookingMeta(b,trips=[]){const trip=trips.find(t=>t.id===b.trip_id);return [label(b.booking_type),b.provider,b.confirmation_reference,trip?trip.title:'Unlinked',b.location].filter(Boolean).map(esc).join(' · ');}
function bookingCard(b,trips){return card(`<div class="card-head"><div><a class="title" href="/bookings/${encodeURIComponent(b.id)}/edit">${esc(b.title)}</a><div class="meta">${bookingMeta(b,trips)}</div></div>${statusChip(b.status)}</div><div class="actions">${buttonLink({href:`/bookings/${encodeURIComponent(b.id)}/edit`,text:'Edit'})}</div>`);}
function renderBookingsPage({bookings=[],trips=[],flash=null}={}){const unlinked=bookings.filter(b=>!b.trip_id),linked=bookings.filter(b=>b.trip_id);const block=rows=>rows.length?`<div class="cards">${rows.map(b=>bookingCard(b,trips)).join('')}</div>`:emptyState('None.');const body=`<div class="page-heading"><h1>Bookings</h1><p class="sub">Travel reservations and confirmations. A booking can exist before it is assigned to a trip.</p></div><div class="actions">${buttonLink({href:'/bookings/new',text:'Add booking',primary:true})}${buttonLink({href:'/trips',text:'Trips'})}</div>${flash?flashMessage(flash):''}<div class="section">Unlinked</div>${block(unlinked)}<div class="section">Linked to trips</div>${block(linked)}`;return renderShell({title:'Bookings',activeNav:'Trips',body});}
function renderBookingFormPage({booking={},trips=[],segments=[],mode='create',error=null}={}){const edit=mode==='edit',action=edit?`/bookings/${encodeURIComponent(booking.id)}`:'/bookings',zone=booking.time_zone||'Australia/Sydney';const sourceLink=booking.source_metadata&&booking.source_metadata.source_link?buttonLink({href:booking.source_metadata.source_link,text:'Open source email'}):'';const body=`<div class="page-heading"><h1>${edit?'Edit booking':'Add booking'}</h1><p class="sub">Store the booking first; link it to a trip when the match is clear.</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:booking.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'booking_type',label:'Booking type',value:booking.booking_type||'other',options:pairs(['flight','accommodation','hire_car','transport','activity','other'])})}${selectField({name:'status',label:'Status',value:booking.status||'confirmed',options:pairs(['confirmed','tentative','changed','cancelled'])})}${selectField({name:'trip_id',label:'Trip',value:booking.trip_id||'',options:tripOptions(trips)})}${selectField({name:'segment_id',label:'Segment',value:booking.segment_id||'',options:segmentOptions(segments)})}${fieldInput({name:'position',label:'Position',value:booking.position||1,type:'number',min:1})}${textField({name:'provider',label:'Provider',value:booking.provider||''})}${textField({name:'confirmation_reference',label:'Confirmation reference',value:booking.confirmation_reference||''})}${fieldInput({name:'starts_at',label:'Starts',value:inputLocal(booking.starts_at,zone),type:'datetime-local'})}${fieldInput({name:'ends_at',label:'Ends',value:inputLocal(booking.ends_at,zone),type:'datetime-local'})}</div>${fieldInput({name:'time_zone',label:'Time zone',value:zone,required:true,list:'booking-time-zones'})}${timeZoneList()}<div class="grid2">${textField({name:'location',label:'Location',value:booking.location||''})}${textField({name:'origin',label:'Origin',value:booking.origin||''})}${textField({name:'destination',label:'Destination',value:booking.destination||''})}${fieldInput({name:'booking_url',label:'Booking URL',value:booking.booking_url||'',type:'url'})}</div>${textareaField({name:'notes',label:'Notes',value:booking.notes||'',rows:5})}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add booking'}</button>${buttonLink({href:'/bookings',text:'Cancel'})}${sourceLink}${edit?`<button class="button danger" type="submit" formaction="/bookings/${encodeURIComponent(booking.id)}/delete">Delete booking</button>`:''}</div></form>`;return renderShell({title:edit?'Edit booking':'Add booking',activeNav:'Trips',body});}
module.exports={renderBookingsPage,renderBookingFormPage};
