'use strict';

const {renderShell,escapeHtml:e}=require('../ui/shell');

function monthLabel(monthKey){const[y,m]=monthKey.split('-').map(Number);return new Intl.DateTimeFormat('en-AU',{timeZone:'UTC',month:'long',year:'numeric'}).format(new Date(Date.UTC(y,m-1,1)));}
function dayNumber(key){return Number(String(key).slice(-2));}
function dayLabel(key){const[y,m,d]=String(key).split('-').map(Number);return new Intl.DateTimeFormat('en-AU',{timeZone:'UTC',weekday:'short',day:'numeric',month:'short'}).format(new Date(Date.UTC(y,m-1,d)));}
function eventTime(item){return item.allDay?'All day':new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',hour:'numeric',minute:'2-digit'}).format(new Date(item.startsAt));}
function eventHtml(item,{agenda=false}={}){const time=eventTime(item);const planned=item.sourceType==='planned_workout';const marker=item.sourceColor?` style="--source:${e(item.sourceColor)}"`:planned?' style="--source:#147a4b"':'';const details=[];if(item.location)details.push(`<span>Location: ${e(item.location)}</span>`);if(planned){const context=[item.sport?e(String(item.sport).replace(/_/g,' ')):null,Number.isFinite(Number(item.durationMinutes))?`${Number(item.durationMinutes)} min`:null,Number.isFinite(Number(item.distanceKm))?`${Number(item.distanceKm)} km`:null].filter(Boolean).join(' · ');if(context)details.push(`<span>${context}</span>`);if(item.description)details.push(`<span>${e(item.description)}</span>`);}if(item.externalUrl)details.push(`<a href="${e(item.externalUrl)}" target="_blank" rel="noopener noreferrer">Open in calendar ↗</a>`);return `<details class="event${planned?' planned-workout':''}${agenda?' agenda-event':''}"${marker}><summary><i></i><span><strong>${e(item.title)}</strong><small>${e(time)} · ${e(item.sourceName)}</small></span></summary>${details.length?`<div class="event-detail">${details.join('')}</div>`:''}</details>`;}
function agendaHtml(days,dataUnavailable){if(dataUnavailable)return'';const populated=Object.entries(days).filter(([,items])=>Array.isArray(items)&&items.length);if(!populated.length)return'<div class="empty calendar-agenda-empty">No events this month.</div>';return populated.map(([key,items])=>`<section class="agenda-day" data-date="${e(key)}"><div class="agenda-date">${e(dayLabel(key))}</div><div class="agenda-events">${items.map(item=>eventHtml(item,{agenda:true})).join('')}</div></section>`).join('');}

function renderCalendarViewPage({month,dataUnavailable=false}={}){
 const safe=month||{monthKey:'',previousMonth:'',nextMonth:'',currentMonth:'',days:{}};const days=safe.days||{};const firstKey=Object.keys(days)[0];let leading=0;if(firstKey){const[y,m,d]=firstKey.split('-').map(Number);const jsDay=new Date(Date.UTC(y,m-1,d)).getUTCDay();leading=(jsDay+6)%7;}
 const cells=`${'<div class="calendar-blank"></div>'.repeat(leading)}${Object.entries(days).map(([key,items])=>`<section class="calendar-day"><div class="calendar-day-num">${dayNumber(key)}</div>${dataUnavailable?'':items.map(item=>eventHtml(item)).join('')}</section>`).join('')}`;
 const body=`<div class="page-heading calendar-heading"><h1>Calendar</h1><p class="sub">Read-only calendar and training context.</p></div><div class="calendar-toolbar"><strong>${e(safe.monthKey?monthLabel(safe.monthKey):'Calendar')}</strong><div class="calendar-nav"><a class="button" href="/calendar?month=${e(safe.previousMonth)}">← Previous</a><a class="button" href="/calendar?month=${e(safe.currentMonth)}">Today</a><a class="button" href="/calendar?month=${e(safe.nextMonth)}">Next →</a><a class="button" href="/settings/calendars">Calendar Settings</a></div></div>${dataUnavailable?'<div class="calendar-unavailable">Calendar data is temporarily unavailable.</div>':''}<div class="calendar-desktop"><div class="calendar-weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-month-grid">${cells}</div></div><div class="calendar-agenda">${agendaHtml(days,dataUnavailable)}</div>`;
 return renderShell({title:'Calendar',activeNav:'Calendar',wide:true,body});
}
module.exports={renderCalendarViewPage};
