const {PRODUCT_NAME}=require('../branding');

function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(value){if(!value)return'Never';try{return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}catch{return'Unknown';}}
function connectionFor(connections,provider){return connections.find(x=>x.provider===provider)||null;}
function sourceRows(connection,sources){
  if(!connection)return'';
  const rows=sources.filter(x=>x.connection_id===connection.id);
  if(!rows.length)return'<p class="muted">No calendars discovered yet.</p>';
  return `<div class="sources">${rows.map(row=>`<form class="source" method="post" action="/settings/calendars/sources/${encodeURIComponent(row.id)}/toggle"><div><strong>${esc(row.display_name)}</strong><span>${row.read_only?'Read only':'Calendar'}</span></div><input type="hidden" name="selected" value="${row.selected?'false':'true'}"><button type="submit">${row.selected?'Included':'Excluded'}</button></form>`).join('')}</div>`;
}
function providerCard(provider,title,connection,sources){
  if(!connection){
    if(provider==='google')return `<section class="card"><h2>${title}</h2><p class="muted">Connect one personal Google Calendar account. Calendar access is separate from Preston sign-in and is read only.</p><a class="button" href="/settings/calendars/google/connect">Connect Google Calendar</a></section>`;
    return `<section class="card"><h2>${title}</h2><p class="muted">Use an Apple app-specific password. Preston never needs your normal Apple Account password.</p><form method="post" action="/settings/calendars/apple/connect"><label>Apple ID email<input name="email" type="email" autocomplete="username" required></label><label>App-specific password<input name="app_specific_password" type="password" autocomplete="current-password" required></label><button type="submit">Connect Apple Calendar</button></form></section>`;
  }
  const disconnect=provider==='google'?'Disconnect Google':'Disconnect Apple';
  return `<section class="card"><div class="card-head"><div><h2>${title}</h2><p class="account">${esc(connection.account_label||'Connected')}</p></div><span class="badge ${connection.status==='connected'?'ok':'warn'}">${esc(connection.status||'connected')}</span></div><p class="muted">Last successful sync: ${esc(fmt(connection.last_success_at))}</p>${connection.last_error?`<p class="error">${esc(connection.last_error)}</p>`:''}${sourceRows(connection,sources)}<form method="post" action="/settings/calendars/${provider}/disconnect"><button class="danger" type="submit">${disconnect}</button></form></section>`;
}

function renderCalendarsPage({connections=[],sources=[],flash=null}={}){
  const google=connectionFor(connections,'google'),apple=connectionFor(connections,'apple');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Calendars · ${PRODUCT_NAME}</title><style>:root{--bg:#eef2f4;--card:#fff;--ink:#122432;--muted:#667781;--line:#d7e0e4;--blue:#075b8e;--green:#147a4b;--red:#a34721;--amber:#9b6414}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:860px;margin:auto;padding:24px 18px 50px}.back{color:var(--blue);font-weight:800;text-decoration:none}h1{font-size:36px;margin:20px 0 5px}.lead,.muted{color:var(--muted)}.flash{background:#e9f6ef;border:1px solid #bddfca;border-radius:10px;padding:10px 12px;margin:16px 0}.actions{display:flex;justify-content:flex-end;margin:16px 0}.card{background:var(--card);border:1px solid var(--line);border-radius:15px;padding:18px;margin:14px 0}.card-head{display:flex;justify-content:space-between;gap:14px}.card h2{margin:0 0 6px}.account{margin:0;font-weight:700}.badge{font-size:11px;font-weight:800;text-transform:uppercase}.badge.ok{color:var(--green)}.badge.warn{color:var(--amber)}label{display:block;font-weight:700;margin:12px 0}input{display:block;width:100%;margin-top:6px;border:1px solid var(--line);border-radius:9px;padding:10px}button,.button{display:inline-block;border:0;background:var(--blue);color:#fff;border-radius:9px;padding:10px 13px;font-weight:800;text-decoration:none;cursor:pointer}.danger{background:var(--red);margin-top:12px}.sources{border-top:1px solid var(--line);margin-top:12px}.source{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:11px 0;border-bottom:1px solid #edf1f3}.source span{display:block;color:var(--muted);font-size:12px;margin-top:2px}.source button{background:#fff;color:var(--blue);border:1px solid var(--line)}.error{color:var(--red);font-weight:700}</style></head><body><main><a class="back" href="/">← Home</a><h1>Calendars</h1><p class="lead">Choose exactly which personal calendars Preston may use in the morning summary. New calendars are excluded by default.</p>${flash?`<div class="flash">${esc(flash)}</div>`:''}<div class="actions"><form method="post" action="/settings/calendars/sync"><button type="submit">Sync calendars</button></form></div>${providerCard('google','Google Calendar',google,sources)}${providerCard('apple','Apple / iCloud Calendar',apple,sources)}</main></body></html>`;
}

module.exports={renderCalendarsPage};
