'use strict';

const { renderShell, escapeHtml } = require('../ui/shell');
const { flashMessage } = require('../ui/components');
const { textField } = require('../ui/forms');

function time(value,fallback){const s=String(value||fallback||'');return s.slice(0,5);}
function dateTime(value){if(!value)return'—';try{return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));}catch{return'—';}}
function offsetEditor(label,name,values=[]){return `<fieldset class="offset-group"><legend>${escapeHtml(label)}</legend><div class="offset-chips">${values.map(value=>`<label class="offset-chip"><span class="sr-only">${escapeHtml(label)} reminder days before</span><input type="number" min="0" step="1" name="${escapeHtml(name)}" value="${escapeHtml(value)}" inputmode="numeric"><span>days</span></label>`).join('')}</div><small>Each chip is a reminder lead time in days.</small></fieldset>`;}
function renderSubscriptions(rows=[]){if(!rows.length)return '<p class="muted">No devices enrolled yet.</p>';return rows.map(row=>`<article class="device"><div><strong>${escapeHtml(row.device_label||'This device')}</strong><span>${row.active?'Enabled':'Disabled'}${row.last_used_at?` · last used ${escapeHtml(dateTime(row.last_used_at))}`:''}</span></div><form method="post" action="/notifications/subscriptions/${encodeURIComponent(row.id)}/toggle"><input type="hidden" name="active" value="${row.active?'false':'true'}"><button class="button" type="submit">${row.active?'Disable':'Enable'}</button></form></article>`).join('');}
function renderHistory(rows=[]){if(!rows.length)return '<p class="muted">No notification delivery history yet.</p>';return rows.slice(0,30).map(row=>`<div class="history"><strong>${escapeHtml(String(row.status||'').replace(/_/g,' '))}</strong><span>${escapeHtml(dateTime(row.attempted_at))}${row.error_category?` · ${escapeHtml(row.error_category)}`:''}</span></div>`).join('');}

function renderNotificationsPage({settings={},subscriptions=[],history=[],vapidPublicKey='',flash=null}={}){
  const quietStart=time(settings.quiet_hours_start,'22:00'),quietEnd=time(settings.quiet_hours_end,'07:00');
  const body=`<div class="page-heading"><h1>Notifications</h1><p class="sub">One morning summary at 07:05, with urgent-only checks later in the day.</p></div>${flash?flashMessage(flash):''}<section class="card notification-card"><h2>Schedule</h2><div class="schedule"><div class="slot"><strong>07:05</strong><span>Daily summary</span></div><div class="slot"><strong>12:00</strong><span>Urgent-only check</span></div><div class="slot"><strong>18:00</strong><span>Urgent-only check</span></div></div><p class="muted">Timezone: ${escapeHtml(settings.timezone||'Australia/Sydney')}</p></section><section class="card notification-card"><h2>Reminder defaults</h2><form method="post" action="/notifications/settings"><div class="quiet-grid">${textField({name:'quiet_hours_start',label:'Quiet hours start',value:quietStart,type:'time'})}${textField({name:'quiet_hours_end',label:'Quiet hours end',value:quietEnd,type:'time'})}</div><div class="offset-grid">${offsetEditor('Birthday','birthday_offsets',settings.birthday_offsets||[30,14,7,1])}${offsetEditor('Renewal / expiry','renewal_offsets',settings.renewal_offsets||[60,30,14,7,1])}${offsetEditor('Bill / deadline','deadline_offsets',settings.deadline_offsets||[14,7,3,0])}${offsetEditor('Appointment / event','appointment_offsets',settings.appointment_offsets||[7,1,0])}${offsetEditor('Trip','trip_offsets',settings.trip_offsets||[14,7,1])}</div><div class="actions"><button class="button primary" type="submit">Save defaults</button></div></form></section><section class="card notification-card"><h2>This device</h2><p class="muted">Notification permission is requested only after you choose to enable it.</p>${textField({name:'device_label',label:'Device label',value:'This device',maxlength:80,id:'device-label'})}<div class="actions"><button class="button primary" type="button" data-enable-notifications data-device-label-source="#device-label" data-vapid-public-key="${escapeHtml(vapidPublicKey)}">Enable notifications on this device</button></div><p class="muted" data-notification-status></p></section><section class="card notification-card"><h2>Devices</h2>${renderSubscriptions(subscriptions)}</section><section class="card notification-card"><h2>Delivery history</h2>${renderHistory(history)}</section>`;
  return renderShell({title:'Notifications',activeNav:'Notifications',body,headExtra:'<link rel="stylesheet" href="/settings.css">',scripts:['/notifications.js']});
}

module.exports={renderNotificationsPage};
