'use strict';

const { utcToLocalDateTime } = require('../domain/trips');
const { renderReminderControls } = require('./reminder-controls');
const { renderShell, escapeHtml: esc } = require('../ui/shell');
const { buttonLink, emptyState, flashMessage, card, statusChip, label } = require('../ui/components');
const { textField, selectField, dateField, textareaField } = require('../ui/forms');

const TIME_ZONES=['Australia/Sydney','Australia/Adelaide','Australia/Darwin','Australia/Perth','Pacific/Auckland','America/Chicago','America/New_York','America/Los_Angeles','UTC'];
const timeZoneList=()=>`<datalist id="time-zones">${TIME_ZONES.map(z=>`<option value="${esc(z)}"></option>`).join('')}</datalist>`;
function inputDate(v){return v?String(v).slice(0,10):'';}
function inputLocal(v,z){try{return v?utcToLocalDateTime(v,z||'Australia/Sydney'):'';}catch{return'';}}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${String(v).slice(0,10)}T00:00:00Z`));}catch{return'Invalid date';}}
function fmtLocal(v,z){if(!v)return'';try{const zone=z||'Australia/Sydney';return `${utcToLocalDateTime(v,zone).replace('T',' ')} · ${zone}`;}catch{return'Invalid time';}}
function tripDates(t){if(!t.start_date&&!t.end_date)return'No dates yet';if(t.start_date&&t.end_date)return`${fmtDate(t.start_date)} – ${fmtDate(t.end_date)}`;return fmtDate(t.start_date||t.end_date);}
function pairs(values){return values.map(v=>[v,label(v)]);}
function fieldInput({name,label:text,value='',type='text',required=false,min,max,placeholder='',list=''}){return `<div class="field"><label for="${esc(name)}">${esc(text)}</label><input id="${esc(name)}" name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"${required?' required':''}${min!==undefined?` min="${esc(min)}"`:''}${max!==undefined?` max="${esc(max)}"`:''}${placeholder?` placeholder="${esc(placeholder)}"`:''}${list?` list="${esc(list)}"`:''}></div>`;}

function renderTripsPage({trips=[],upcoming=[],flash=null}={}){
  const cards=trips.length?`<div class="cards">${trips.map(t=>card(`<div class="card-head"><div><a class="title" href="/trips/${encodeURIComponent(t.id)}">${esc(t.title)}</a><div class="meta">${esc(tripDates(t))}</div></div>${statusChip(t.status)}</div>${t.notes?`<div class="notes">${esc(t.notes)}</div>`:''}`)).join('')}</div>`:emptyState('No trips yet.');
  const up=upcoming.length?`<div class="panel">${upcoming.map(t=>`<a class="row row-link" href="/trips/${encodeURIComponent(t.id)}"><span class="title">${esc(t.title)}</span><span class="meta">${esc(fmtDate(t.start_date))}</span></a>`).join('')}</div>`:emptyState('No upcoming trips.');
  const body=`<div class="page-heading"><h1>Trips</h1><p class="sub">Travel plans, bookings and the itinerary generated from what you actually stored.</p></div>${buttonLink({href:'/trips/new',text:'Add trip',primary:true})}${flash?flashMessage(flash):''}<div class="section">Coming Up</div>${up}<div class="section">All Trips</div>${cards}`;
  return renderShell({title:'Trips',activeNav:'Trips',body});
}

function itineraryRow(entry){
  const r=entry.record;const kind=entry.type==='booking'?r.booking_type:r.segment_type;const when=fmtLocal(r.starts_at,r.time_zone);const meta=[label(kind),entry.type==='booking'?label(r.status):null,when].filter(Boolean).join(' · ');
  const href=entry.type==='booking'?`/bookings/${encodeURIComponent(r.id)}/edit`:`/segments/${encodeURIComponent(r.id)}/edit`;
  return `<a class="row row-link" href="${href}"><div><strong>${esc(r.title)}</strong><div class="meta">${esc(meta)}</div></div><span class="row-action">Edit</span></a>`;
}
function bookingCard(b){return card(`<div class="card-head"><div><strong class="title">${esc(b.title)}</strong><div class="meta">${[label(b.booking_type),b.provider,b.confirmation_reference].filter(Boolean).map(esc).join(' · ')}</div></div>${statusChip(b.status)}</div><div class="actions">${buttonLink({href:`/bookings/${encodeURIComponent(b.id)}/edit`,text:'Edit'})}<form method="post" action="/bookings/${encodeURIComponent(b.id)}/delete" onsubmit="return confirm('Delete this booking?')"><button class="button danger" type="submit">Delete booking</button></form></div>`);}
function taskRows(tasks){return tasks.length?`<div class="panel">${tasks.map(t=>`<a class="row row-link task-row" href="/tasks/${encodeURIComponent(t.id)}/edit"><div><strong>${esc(t.title)}</strong><div class="meta">${esc(label(t.status))} · ${esc(label(t.priority))}</div></div><span class="row-action">Edit</span></a>`).join('')}</div>`:emptyState('No tasks linked to this trip.');}
function managePanel(trip,segments){const segmentRows=segments.length?segments.map(s=>`<div class="manage-row"><div><strong>${esc(s.title)}</strong><div class="meta">${esc(label(s.segment_type))}${fmtLocal(s.starts_at,s.time_zone)?` · ${esc(fmtLocal(s.starts_at,s.time_zone))}`:''}</div></div><div class="actions">${buttonLink({href:`/segments/${encodeURIComponent(s.id)}/edit`,text:'Edit'})}<form method="post" action="/segments/${encodeURIComponent(s.id)}/delete" onsubmit="return confirm('Delete this segment?')"><button class="button danger" type="submit">Delete</button></form></div></div>`).join(''):'<div class="meta">No segments yet.</div>';return `<details class="manage-panel"><summary>Manage trip</summary><div class="manage-actions">${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}/edit`,text:'Edit trip'})}${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}/segments/new`,text:'Add segment'})}${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}/bookings/new`,text:'Add booking'})}${buttonLink({href:`/tasks/new?trip_id=${encodeURIComponent(trip.id)}`,text:'Add task'})}</div><div class="manage-list">${segmentRows}</div><form method="post" action="/trips/${encodeURIComponent(trip.id)}/delete" onsubmit="return confirm('Delete this trip?')"><button class="button danger" type="submit">Delete trip</button></form></details>`;}
function renderTripDetailPage({trip,segments=[],bookings=[],itinerary=[],tasks=[]}={}){
  if(!trip)return renderShell({title:'Trips',activeNav:'Trips',body:'<div class="page-heading"><h1>Trips</h1></div>'+emptyState('Trip not found.')});
  const its=itinerary.length?`<div class="panel">${itinerary.map(itineraryRow).join('')}</div>`:emptyState('No itinerary entries yet.');
  const next=itinerary[0]?`<article class="next-card"><span class="eyebrow">Next</span><strong>${esc(itinerary[0].record.title)}</strong><div class="meta">${esc(fmtLocal(itinerary[0].record.starts_at,itinerary[0].record.time_zone)||label(itinerary[0].type))}</div></article>`:'';
  const books=bookings.length?`<div class="cards">${bookings.map(bookingCard).join('')}</div>`:emptyState('No bookings yet.');
  const body=`<div class="page-heading"><h1>${esc(trip.title)}</h1><p class="sub">${esc(label(trip.status))} · ${esc(tripDates(trip))}</p></div>${trip.notes?`<div class="panel notes trip-notes">${esc(trip.notes)}</div>`:''}${next?`<div class="section">Next</div>${next}`:''}<div class="section">Itinerary</div>${its}<div class="section">Bookings</div>${books}<div class="section">Linked Tasks</div>${taskRows(tasks)}<div class="section">Manage trip</div>${managePanel(trip,segments)}`;
  return renderShell({title:trip.title,activeNav:'Trips',body});
}

function renderTripFormPage({trip={},mode='create',error=null,reminderSettings={},reminderOverride=null}={}){
  const edit=mode==='edit',action=edit?`/trips/${encodeURIComponent(trip.id)}`:'/trips';const reminderControls=renderReminderControls({reminderClass:'trip',settings:reminderSettings,override:reminderOverride,edit});
  const body=`<div class="page-heading"><h1>${edit?'Edit trip':'Add trip'}</h1><p class="sub">Create the trip shell first; add itinerary details afterward.</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:trip.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'status',label:'Status',value:trip.status||'planning',options:pairs(['planning','upcoming','in_progress','completed','cancelled'])})}${dateField({name:'start_date',label:'Start date',value:inputDate(trip.start_date)})}${dateField({name:'end_date',label:'End date',value:inputDate(trip.end_date)})}</div>${textareaField({name:'notes',label:'Notes',value:trip.notes||'',rows:5})}${reminderControls}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add trip'}</button>${buttonLink({href:edit?`/trips/${encodeURIComponent(trip.id)}`:'/trips',text:'Cancel'})}</div></form>`;
  return renderShell({title:edit?'Edit trip':'Add trip',activeNav:'Trips',body});
}

function renderSegmentFormPage({segment={},trip,mode='create',error=null}={}){
  const edit=mode==='edit',action=edit?`/segments/${encodeURIComponent(segment.id)}`:`/trips/${encodeURIComponent(trip.id)}/segments`,zone=segment.time_zone||'Australia/Sydney';
  const body=`<div class="page-heading"><h1>${edit?'Edit segment':'Add segment'}</h1><p class="sub">${esc(trip.title)}</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:segment.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'segment_type',label:'Type',value:segment.segment_type||'travel',options:pairs(['travel','stay','activity','other'])})}${fieldInput({name:'position',label:'Position',value:segment.position||1,type:'number',min:1})}${textField({name:'origin',label:'Origin',value:segment.origin||''})}${textField({name:'destination',label:'Destination',value:segment.destination||''})}${fieldInput({name:'starts_at',label:'Starts',value:inputLocal(segment.starts_at,zone),type:'datetime-local'})}${fieldInput({name:'ends_at',label:'Ends',value:inputLocal(segment.ends_at,zone),type:'datetime-local'})}</div>${fieldInput({name:'time_zone',label:'Time zone',value:zone,required:true,placeholder:'Australia/Sydney',list:'time-zones'})}${timeZoneList()}${textareaField({name:'notes',label:'Notes',value:segment.notes||'',rows:5})}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add segment'}</button>${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}`,text:'Cancel'})}</div></form>`;
  return renderShell({title:edit?'Edit segment':'Add segment',activeNav:'Trips',body});
}

function segmentOptions(segments){return [['','None'],...segments.map(s=>[s.id,s.title])];}
function renderBookingFormPage({booking={},trip,segments=[],mode='create',error=null}={}){
  const edit=mode==='edit',action=edit?`/bookings/${encodeURIComponent(booking.id)}`:`/trips/${encodeURIComponent(trip.id)}/bookings`,zone=booking.time_zone||'Australia/Sydney';
  const body=`<div class="page-heading"><h1>${edit?'Edit booking':'Add booking'}</h1><p class="sub">${esc(trip.title)} · manual booking</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:booking.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'booking_type',label:'Booking type',value:booking.booking_type||'other',options:pairs(['flight','accommodation','hire_car','activity','other'])})}${selectField({name:'status',label:'Status',value:booking.status||'confirmed',options:pairs(['confirmed','tentative','changed','cancelled'])})}${fieldInput({name:'position',label:'Position',value:booking.position||1,type:'number',min:1})}${selectField({name:'segment_id',label:'Segment',value:booking.segment_id||'',options:segmentOptions(segments)})}${textField({name:'provider',label:'Provider',value:booking.provider||''})}${textField({name:'confirmation_reference',label:'Confirmation reference',value:booking.confirmation_reference||''})}${fieldInput({name:'starts_at',label:'Starts',value:inputLocal(booking.starts_at,zone),type:'datetime-local'})}${fieldInput({name:'ends_at',label:'Ends',value:inputLocal(booking.ends_at,zone),type:'datetime-local'})}</div>${fieldInput({name:'time_zone',label:'Time zone',value:zone,required:true,list:'time-zones'})}${timeZoneList()}${textField({name:'location',label:'Location',value:booking.location||''})}${fieldInput({name:'booking_url',label:'Booking URL',value:booking.booking_url||'',type:'url'})}${textareaField({name:'notes',label:'Notes',value:booking.notes||'',rows:5})}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add booking'}</button>${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}`,text:'Cancel'})}</div></form>`;
  return renderShell({title:edit?'Edit booking':'Add booking',activeNav:'Trips',body});
}

module.exports={renderTripsPage,renderTripDetailPage,renderTripFormPage,renderSegmentFormPage,renderBookingFormPage,esc,fmtDate,fmtLocal};
