'use strict';

const {utcToLocalDateTime}=require('../domain/trips');
const {renderReminderControls}=require('./reminder-controls');
const {renderShell,escapeHtml:esc}=require('../ui/shell');
const {buttonLink,emptyState,flashMessage,card,statusChip,label}=require('../ui/components');
const {textField,selectField,dateField,textareaField}=require('../ui/forms');

const TIME_ZONES=['Australia/Sydney','Australia/Adelaide','Australia/Darwin','Australia/Perth','Pacific/Auckland','America/Chicago','America/New_York','America/Los_Angeles','UTC'];
const timeZoneList=()=>`<datalist id="time-zones">${TIME_ZONES.map(z=>`<option value="${esc(z)}"></option>`).join('')}</datalist>`;
function inputDate(v){return v?String(v).slice(0,10):'';}
function inputLocal(v,z){try{return v?utcToLocalDateTime(v,z||'Australia/Sydney'):'';}catch{return'';}}
function fmtDate(v){if(!v)return'';try{return new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${String(v).slice(0,10)}T00:00:00Z`));}catch{return'Invalid date';}}
function fmtShort(v,z='Australia/Sydney'){if(!v)return'';try{return new Intl.DateTimeFormat('en-AU',{timeZone:z,day:'numeric',month:'short'}).format(new Date(v));}catch{return'';}}
function fmtLocal(v,z){if(!v)return'';try{const zone=z||'Australia/Sydney';return `${utcToLocalDateTime(v,zone).replace('T',' ')} · ${zone}`;}catch{return'Invalid time';}}
function tripDates(t){if(!t.start_date&&!t.end_date)return'No dates yet';if(t.start_date&&t.end_date)return`${fmtDate(t.start_date)} – ${fmtDate(t.end_date)}`;return fmtDate(t.start_date||t.end_date);}
function pairs(values){return values.map(v=>[v,label(v)]);}
function fieldInput({name,label:text,value='',type='text',required=false,min,max,placeholder='',list=''}){return `<div class="field"><label for="${esc(name)}">${esc(text)}</label><input id="${esc(name)}" name="${esc(name)}" type="${esc(type)}" value="${esc(value)}"${required?' required':''}${min!==undefined?` min="${esc(min)}"`:''}${max!==undefined?` max="${esc(max)}"`:''}${placeholder?` placeholder="${esc(placeholder)}"`:''}${list?` list="${esc(list)}"`:''}></div>`;}

function tripCard(t){return card(`<div class="card-head"><div><a class="title" href="/trips/${encodeURIComponent(t.id)}">${esc(t.title)}</a><div class="meta">${[t.destination_label,tripDates(t),t.archived_at?'Archived':null].filter(Boolean).map(esc).join(' · ')}</div></div>${statusChip(t.status)}</div>${t.notes?`<div class="notes">${esc(t.notes)}</div>`:''}`);}
function tripCards(rows,message){return rows.length?`<div class="cards">${rows.map(tripCard).join('')}</div>`:emptyState(message);}
function renderTripsPage({trips=[],upcoming=[],past=[],archived=false,flash=null}={}){
  if(archived){const body=`<div class="page-heading"><h1>Archived Trips</h1><p class="sub">Historical trips kept with all of their bookings, events, tasks and stages.</p></div><div class="actions">${buttonLink({href:'/trips',text:'Back to Trips'})}</div>${flash?flashMessage(flash):''}${tripCards(trips,'No archived trips.')}`;return renderShell({title:'Archived Trips',activeNav:'Trips',body});}
  const body=`<div class="page-heading"><h1>Trips</h1><p class="sub">Travel plans, bookings and itinerary details.</p></div><div class="actions">${buttonLink({href:'/trips/new',text:'Add trip',primary:true})}${buttonLink({href:'/trips/archived',text:'Archived Trips'})}</div>${flash?flashMessage(flash):''}<div class="section">Coming Up</div>${tripCards(upcoming,'No upcoming trips.')}<div class="section">Past trips</div>${tripCards(past,'No past unarchived trips.')}`;
  return renderShell({title:'Trips',activeNav:'Trips',body});
}

function legRows(booking,bookingLegs=[]){const legs=bookingLegs.filter(x=>x.booking_id===booking.id).sort((a,b)=>Number(a.position||1)-Number(b.position||1));if(!legs.length)return'';return `<div class="travel-legs">${legs.map(leg=>`<div class="travel-leg"><span class="travel-badge">FLIGHT</span>${leg.service_number?` <strong>${esc(leg.service_number)}</strong>`:''}${leg.origin||leg.destination?` <span class="meta">${esc(leg.origin||'')} → ${esc(leg.destination||'')}</span>`:''}${leg.departs_at?` <span class="meta">${esc(fmtShort(leg.departs_at,leg.departure_time_zone||booking.time_zone))}</span>`:''}</div>`).join('')}</div>`;}
function bookingCard(b,bookingLegs=[]){const type=String(b.booking_type||'other').toUpperCase().replace('_',' ');return card(`<div class="card-head"><div><span class="travel-badge">${esc(type)}</span><strong class="title">${esc(b.title)}</strong><div class="meta">${[b.provider,b.confirmation_reference?`Ref ${b.confirmation_reference}`:null].filter(Boolean).map(esc).join(' · ')}</div></div>${statusChip(b.status)}</div>${legRows(b,bookingLegs)}<div class="actions">${buttonLink({href:`/bookings/${encodeURIComponent(b.id)}/edit`,text:'Edit'})}</div>`);}
function itineraryRow(entry,bookingLegs=[]){const r=entry.record;if(entry.type==='event'){const meta=[r.provider||'Event',r.location,fmtLocal(r.starts_at,r.time_zone),r.confirmation_reference?`Ref ${r.confirmation_reference}`:null].filter(Boolean).join(' · ');return `<a class="row row-link" href="/life-admin/${encodeURIComponent(r.id)}"><div><span class="travel-badge">EVENT</span><strong>${esc(r.title)}</strong><div class="meta">${esc(meta)}</div></div><span class="row-action">Open</span></a>`;}if(entry.type==='booking'){const legs=legRows(r,bookingLegs);const meta=[label(r.booking_type),label(r.status),r.provider,r.confirmation_reference?`Ref ${r.confirmation_reference}`:null].filter(Boolean).join(' · ');return `<div class="row"><div><span class="travel-badge">${esc(String(r.booking_type||'booking').toUpperCase().replace('_',' '))}</span><strong>${esc(r.title)}</strong><div class="meta">${esc(meta)}</div>${legs}</div>${buttonLink({href:`/bookings/${encodeURIComponent(r.id)}/edit`,text:'Edit'})}</div>`;}const meta=[label(r.segment_type),fmtLocal(r.starts_at,r.time_zone)].filter(Boolean).join(' · ');return `<a class="row row-link" href="/segments/${encodeURIComponent(r.id)}/edit"><div><span class="travel-badge">STAGE</span><strong>${esc(r.title)}</strong><div class="meta">${esc(meta)}</div></div><span class="row-action">Edit</span></a>`;}
function taskRows(tasks){return tasks.length?`<div class="panel">${tasks.map(t=>`<a class="row row-link task-row" href="/tasks/${encodeURIComponent(t.id)}/edit"><div><strong>${esc(t.title)}</strong><div class="meta">${esc(label(t.status))} · ${esc(label(t.priority))}</div></div><span class="row-action">Edit</span></a>`).join('')}</div>`:emptyState('No tasks linked to this trip.');}
function managePanel(trip,segments){const stageRows=segments.length?segments.map(s=>`<div class="manage-row"><div><strong>${esc(s.title)}</strong><div class="meta">Stage · ${esc(label(s.segment_type))}${fmtLocal(s.starts_at,s.time_zone)?` · ${esc(fmtLocal(s.starts_at,s.time_zone))}`:''}</div></div><div class="actions">${buttonLink({href:`/segments/${encodeURIComponent(s.id)}/edit`,text:'Edit stage'})}<form method="post" action="/segments/${encodeURIComponent(s.id)}/delete" onsubmit="return confirm('Delete this stage?')"><button class="button danger" type="submit">Delete stage</button></form></div></div>`).join(''):'<div class="meta">No stages yet.</div>';const archiveAction=trip.archived_at?`<form method="post" action="/trips/${encodeURIComponent(trip.id)}/unarchive"><button class="button" type="submit">Unarchive trip</button></form>`:`<form method="post" action="/trips/${encodeURIComponent(trip.id)}/archive"><button class="button" type="submit">Archive trip</button></form>`;return `<details class="manage-panel"><summary>Manage trip</summary><div class="manage-actions">${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}/edit`,text:'Edit trip'})}${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}/segments/new`,text:'Add stage'})}${buttonLink({href:`/bookings/new?trip_id=${encodeURIComponent(trip.id)}`,text:'Add booking'})}${buttonLink({href:`/tasks/new?trip_id=${encodeURIComponent(trip.id)}`,text:'Add task'})}${archiveAction}</div><div class="manage-list">${stageRows}</div><form method="post" action="/trips/${encodeURIComponent(trip.id)}/delete" onsubmit="return confirm('Delete this trip?')"><button class="button danger" type="submit">Delete trip</button></form></details>`;}
function renderTripDetailPage({trip,segments=[],bookings=[],events=[],itinerary=[],bookingLegs=[],inventory=[],nextEntry=null,tasks=[]}={}){
  if(!trip)return renderShell({title:'Trips',activeNav:'Trips',body:'<div class="page-heading"><h1>Trips</h1></div>'+emptyState('Trip not found.')});
  const its=itinerary.length?`<div class="panel">${itinerary.map(entry=>itineraryRow(entry,bookingLegs)).join('')}</div>`:emptyState('No itinerary entries yet.');
  const next=nextEntry?`<article class="next-card"><span class="eyebrow">Next</span><strong>${esc(nextEntry.record.title)}</strong><div class="meta">${esc(fmtLocal(nextEntry.record.starts_at,nextEntry.record.time_zone)||label(nextEntry.type))}</div></article>`:'';
  const books=bookings.length?`<div class="cards">${bookings.map(b=>bookingCard(b,bookingLegs)).join('')}</div>`:emptyState('No bookings yet.');
  const sub=[label(trip.status),trip.destination_label,tripDates(trip),trip.archived_at?'Archived':null].filter(Boolean).map(esc).join(' · ');const inventoryLine=inventory.length?`<div class="meta trip-inventory">${inventory.map(esc).join(' · ')}</div>`:'';
  const body=`<div class="page-heading"><h1>${esc(trip.title)}</h1><p class="sub">${sub}</p>${inventoryLine}</div>${trip.notes?`<div class="panel notes trip-notes">${esc(trip.notes)}</div>`:''}${next?`<div class="section">Next</div>${next}`:''}<div class="section">Itinerary</div>${its}<div class="section">Bookings</div>${books}<div class="section">Linked Tasks</div>${taskRows(tasks)}<div class="section">Manage trip</div>${managePanel(trip,segments)}`;
  return renderShell({title:trip.title,activeNav:'Trips',body});
}

function renderTripFormPage({trip={},mode='create',error=null,reminderSettings={},reminderOverride=null}={}){const edit=mode==='edit',action=edit?`/trips/${encodeURIComponent(trip.id)}`:'/trips';const reminderControls=renderReminderControls({reminderClass:'trip',settings:reminderSettings,override:reminderOverride,edit});const body=`<div class="page-heading"><h1>${edit?'Edit trip':'Add trip'}</h1><p class="sub">Name the trip and store its real destination separately from booking confirmations.</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:trip.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'status',label:'Status',value:trip.status||'planning',options:pairs(['planning','upcoming','in_progress','completed','cancelled'])})}${dateField({name:'start_date',label:'Start date',value:inputDate(trip.start_date)})}${dateField({name:'end_date',label:'End date',value:inputDate(trip.end_date)})}</div><div class="grid2">${textField({name:'destination_label',label:'Destination',value:trip.destination_label||'',placeholder:'e.g. Chicago, IL'})}${textField({name:'destination_city',label:'City',value:trip.destination_city||''})}${textField({name:'destination_region',label:'State / region',value:trip.destination_region||''})}${textField({name:'destination_country',label:'Country',value:trip.destination_country||''})}</div>${textareaField({name:'notes',label:'Notes',value:trip.notes||'',rows:5})}${reminderControls}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add trip'}</button>${buttonLink({href:edit?`/trips/${encodeURIComponent(trip.id)}`:'/trips',text:'Cancel'})}</div></form>`;return renderShell({title:edit?'Edit trip':'Add trip',activeNav:'Trips',body});}
function renderSegmentFormPage({segment={},trip,mode='create',error=null}={}){const edit=mode==='edit',action=edit?`/segments/${encodeURIComponent(segment.id)}`:`/trips/${encodeURIComponent(trip.id)}/segments`,zone=segment.time_zone||'Australia/Sydney';const body=`<div class="page-heading"><h1>${edit?'Edit stage':'Add stage'}</h1><p class="sub">${esc(trip.title)}</p></div>${error?`<div class="flash flash-error" role="alert">${esc(error)}</div>`:''}<form class="editor" method="post" action="${action}">${textField({name:'title',label:'Title',value:segment.title||'',required:true,maxlength:240})}<div class="grid2">${selectField({name:'segment_type',label:'Stage type',value:segment.segment_type||'travel',options:pairs(['travel','stay','activity','other'])})}${fieldInput({name:'position',label:'Position',value:segment.position||1,type:'number',min:1})}${textField({name:'origin',label:'Origin',value:segment.origin||''})}${textField({name:'destination',label:'Destination',value:segment.destination||''})}${fieldInput({name:'starts_at',label:'Starts',value:inputLocal(segment.starts_at,zone),type:'datetime-local'})}${fieldInput({name:'ends_at',label:'Ends',value:inputLocal(segment.ends_at,zone),type:'datetime-local'})}</div>${fieldInput({name:'time_zone',label:'Time zone',value:zone,required:true,placeholder:'Australia/Sydney',list:'time-zones'})}${timeZoneList()}${textareaField({name:'notes',label:'Notes',value:segment.notes||'',rows:5})}<div class="actions"><button class="button primary" type="submit">${edit?'Save changes':'Add stage'}</button>${buttonLink({href:`/trips/${encodeURIComponent(trip.id)}`,text:'Cancel'})}</div></form>`;return renderShell({title:edit?'Edit stage':'Add stage',activeNav:'Trips',body});}

module.exports={renderTripsPage,renderTripDetailPage,renderTripFormPage,renderSegmentFormPage,esc,fmtDate,fmtLocal};
